// ============================================================
// SAAL - BANCO DE ACTIVIDADES (VERSIÓN DEFINITIVA)
// Primaria (1° a 6°) + Secundaria (1° a 3°)
// Formato: area, nivel, nombre, duracion, descripcion, materiales, grado
// ============================================================

const bancoActividades = [

    // ============================================================
    // PRIMARIA
    // ============================================================

    // ------------------------------------------------------------
    // FLUIDEZ — NIVEL 1
    // ------------------------------------------------------------
    { "area": "Fluidez", "nivel": 1, "nombre": "Lectura en eco", "duracion": 5, "descripcion": "El docente lee una frase corta con buena entonación y el alumno la repite inmediatamente, imitando el ritmo, la velocidad y la entonación.", "materiales": ["Texto guía del docente con frases cortas"], "grado": "1°" },
    { "area": "Fluidez", "nivel": 1, "nombre": "Lectura con el dedo", "duracion": 5, "descripcion": "El alumno desliza su dedo índice debajo de las palabras mientras lee en voz baja o susurrada para mantener el ritmo visual.", "materiales": ["Texto individual con letra grande", "Dedo o señalador"], "grado": "1°" },
    { "area": "Fluidez", "nivel": 1, "nombre": "El eco de volumen", "duracion": 5, "descripcion": "El docente lee una palabra en voz baja y el alumno la repite; luego en voz alta y el alumno repite. Control de intensidad.", "materiales": ["Lista de palabras/frases cortas"], "grado": "1°" },
    { "area": "Fluidez", "nivel": 1, "nombre": "Ronda de rimas", "duracion": 10, "descripcion": "El docente escribe y lee una rima corta. Los alumnos la repiten varias veces, aumentando gradualmente la velocidad.", "materiales": ["Rima corta en el pizarrón o en una tarjeta"], "grado": "1°" },
    { "area": "Fluidez", "nivel": 1, "nombre": "Lectura por minuto (Nivel 1)", "duracion": 10, "descripcion": "El alumno lee un texto muy corto durante 1 minuto. El docente cuenta cuántas palabras leyó y lo registra.", "materiales": ["Texto corto (50-80 palabras)", "Cronómetro"], "grado": "1°" },
    { "area": "Fluidez", "nivel": 1, "nombre": "El sonido de los animales", "duracion": 5, "descripcion": "El docente lee un texto y los alumnos hacen el sonido del animal mencionado. Se usa la voz para imitar.", "materiales": ["Texto con animales"], "grado": "1°" },
    { "area": "Fluidez", "nivel": 1, "nombre": "La frase de hoy: repetición guiada", "duracion": 5, "descripcion": "El docente escribe una frase corta (5-6 palabras) en el pizarrón. La lee en voz alta 3 veces mientras los alumnos la siguen con el dedo. Luego los alumnos la repiten al unísono 3 veces. Después, 3 alumnos voluntarios la leen individualmente. La frase se mantiene visible durante toda la sesión.", "materiales": ["Pizarrón", "Marcador"], "grado": "1°" },
    { "area": "Fluidez", "nivel": 1, "nombre": "El tren de las palabras conocidas", "duracion": 5, "descripcion": "El docente prepara tarjetas con palabras que los alumnos ya conocen (nombre propio, familia, colores). Cada alumno toma una tarjeta, la lee en voz alta y la coloca en el 'tren' (hilera). El siguiente alumno lee su palabra y la coloca junto a la anterior. Al final, leen todo el tren de palabras en orden.", "materiales": ["Tarjetas con palabras conocidas (al menos 2 por alumno)"], "grado": "1°" },
    { "area": "Fluidez", "nivel": 1, "nombre": "El eco de palabras", "duracion": 5, "descripcion": "El docente dice una palabra, los alumnos la repiten como un eco. El docente la dice de nuevo con diferente entonación (alegre, triste, sorprendido) y los alumnos la repiten imitando la entonación. Se repite con 5-6 palabras.", "materiales": ["Lista de palabras cortas (2-3 sílabas) con imágenes"], "grado": "1°" },
    { "area": "Fluidez", "nivel": 1, "nombre": "El lector del día", "duracion": 5, "descripcion": "Cada día se elige a un alumno para ser 'el lector del día'. El docente le da un texto muy corto (3-4 oraciones) que el alumno ha practicado previamente con el docente durante el recreo o en un momento de apoyo. El lector del día lee su texto al grupo, con el docente a su lado para apoyarlo en caso necesario. Después recibe un aplauso.", "materiales": ["Texto corto para cada lector del día"], "grado": "1°" },
    { "area": "Fluidez", "nivel": 1, "nombre": "Las sílabas saltarinas", "duracion": 5, "descripcion": "El docente escribe sílabas en el pizarrón (ma, me, mi, mo, mu). Los alumnos las leen en coro. Luego el docente forma palabras combinando sílabas (ma-má, me-sa) y los alumnos las leen. Finalmente, los alumnos leen la palabra completa y dan un salto por cada sílaba.", "materiales": ["Pizarrón", "Marcador", "Tarjetas con sílabas"], "grado": "1°" },
    { "area": "Fluidez", "nivel": 1, "nombre": "El libro de las frases favoritas", "duracion": 10, "descripcion": "El docente y los alumnos eligen 5 frases que les gusten (de canciones, cuentos o dichos populares). Las escriben en un 'libro' grande (rotafolios). Cada día leen una frase en voz alta, con el docente modelando la entonación y el ritmo. Después de una semana, los alumnos pueden leer todas las frases.", "materiales": ["Rotafolios o pliegos de papel", "Marcadores de colores"], "grado": "1°" },
    { "area": "Fluidez", "nivel": 1, "nombre": "La ruleta de palabras rápidas", "duracion": 5, "descripcion": "El docente prepara una ruleta con 6-8 palabras sencillas. Un alumno gira la ruleta, lee la palabra que señale y la usa en una oración (con ayuda del docente si es necesario). El grupo repite la oración. Se repite con 3-4 alumnos.", "materiales": ["Ruleta con palabras", "Tarjetas con las mismas palabras de apoyo"], "grado": "1°" },
    { "area": "Fluidez", "nivel": 1, "nombre": "Mi frase con ritmo", "duracion": 5, "descripcion": "El docente escribe una frase corta. La lee con un ritmo de palmadas (ej. ¡Ma-ña-na-vi-a-re-mos!). Los alumnos repiten la frase con el mismo ritmo. Después, el docente cambia el ritmo (lento, rápido) y los alumnos la leen siguiendo el nuevo ritmo.", "materiales": ["Pizarrón", "Lista de frases cortas"], "grado": "1°" },

    // ------------------------------------------------------------
    // FLUIDEZ — NIVEL 2
    // ------------------------------------------------------------
    { "area": "Fluidez", "nivel": 2, "nombre": "Lectura en eco grupal", "duracion": 10, "descripcion": "El docente lee una estrofa o párrafo y todo el grupo lo repite al unísono. Luego se divide en dos mitades que leen alternando.", "materiales": ["Poema o canción escrita", "Pizarra"], "grado": "2°" },
    { "area": "Fluidez", "nivel": 2, "nombre": "Lectura por minuto (Nivel 2)", "duracion": 15, "descripcion": "El alumno lee un texto durante 1 minuto, cuenta las palabras leídas correctamente y anota su marca. Vuelve a leer para superar su propia marca.", "materiales": ["Texto corto (100-150 palabras)", "Cronómetro", "Registro de marcas"], "grado": "2°" },
    { "area": "Fluidez", "nivel": 2, "nombre": "Carrera de trabalenguas (fluidez)", "duracion": 10, "descripcion": "Se practica un trabalenguas en voz baja, luego en voz media y finalmente en voz alta, cuidando la dicción sin perder la velocidad.", "materiales": ["Tarjetas con trabalenguas"], "grado": "2°" },
    { "area": "Fluidez", "nivel": 2, "nombre": "El noticiero", "duracion": 10, "descripcion": "Cada alumno prepara la lectura de un párrafo de una noticia como si fuera un locutor. Se enfatiza claridad, velocidad y entonación.", "materiales": ["Noticias cortas", "Micrófono de juguete (opcional)"], "grado": "2°" },
    { "area": "Fluidez", "nivel": 2, "nombre": "La noticia en voz alta", "duracion": 15, "descripcion": "Los alumnos practican la lectura en voz alta de una noticia corta, cuidando la pronunciación y el ritmo. Luego la leen para un compañero.", "materiales": ["Noticia corta impresa (1 por alumno)"], "grado": "2°" },
    { "area": "Fluidez", "nivel": 2, "nombre": "Rimas y lectura", "duracion": 10, "descripcion": "Los alumnos repiten una rima oralmente, luego la señalan en el pizarrón mientras la repiten. Se trabaja la correspondencia entre lo oral y lo escrito.", "materiales": ["Rima escrita en el pizarrón"], "grado": "1°" },
    { "area": "Fluidez", "nivel": 2, "nombre": "El cancionero", "duracion": 15, "descripcion": "Los alumnos leen y cantan canciones escritas, señalando las palabras mientras cantan. Se trabaja la correspondencia sonoro-gráfica.", "materiales": ["Cancionero o canciones escritas"], "grado": "1°" },
    { "area": "Fluidez", "nivel": 2, "nombre": "¡A disfrutar de la poesía!", "duracion": 15, "descripcion": "El docente declama poemas con pronunciación, ritmo y entonación adecuados. Los alumnos repiten y practican la declamación.", "materiales": ["Libros de poesía"], "grado": "1°" },

    // ------------------------------------------------------------
    // FLUIDEZ — NIVEL 3
    // ------------------------------------------------------------
    { "area": "Fluidez", "nivel": 3, "nombre": "Teatro de voces (fluidez)", "duracion": 15, "descripcion": "Se asigna un personaje a cada alumno. Leen un diálogo poniendo énfasis en la expresividad, velocidad y volumen según el personaje.", "materiales": ["Guión de diálogo corto", "Tarjetas de personajes"], "grado": "3°" },
    { "area": "Fluidez", "nivel": 3, "nombre": "Lectura expresiva con emociones", "duracion": 15, "descripcion": "El alumno recibe un mismo párrafo y debe leerlo expresando diferentes emociones (alegría, tristeza, enojo, miedo).", "materiales": ["Texto de un párrafo", "Tarjetas de emociones"], "grado": "3°" },
    { "area": "Fluidez", "nivel": 3, "nombre": "Poesía coral", "duracion": 15, "descripcion": "El grupo ensaya y presenta un poema de forma coral, asignando versos a diferentes voces para lograr un efecto rítmico y expresivo.", "materiales": ["Poema", "Marcadores para resaltar partes"], "grado": "3°" },
    { "area": "Fluidez", "nivel": 3, "nombre": "Grabación y autoevaluación", "duracion": 15, "descripcion": "El alumno se graba leyendo un texto. Luego escucha su grabación y se autoevalúa en aspectos de fluidez, entonación y ritmo.", "materiales": ["Texto", "Grabadora (celular)"], "grado": "4°" },
    { "area": "Fluidez", "nivel": 3, "nombre": "El locutor deportivo", "duracion": 10, "descripcion": "El alumno lee una narración de un partido o una noticia deportiva con la emoción y velocidad de un locutor profesional.", "materiales": ["Narración o noticia deportiva"], "grado": "4°" },
    { "area": "Fluidez", "nivel": 3, "nombre": "¡Vamos a cantar! (4°)", "duracion": 15, "descripcion": "Los alumnos aplican sus conocimientos sobre signos de puntuación al escribir una canción. Seleccionan, escriben y revisan la puntuación de una canción.", "materiales": ["Cancioneros", "Pizarrón", "Cuaderno"], "grado": "4°" },
    { "area": "Fluidez", "nivel": 3, "nombre": "Lo que me contó el abuelo", "duracion": 15, "descripcion": "Los alumnos desarrollan la habilidad para deleitar, persuadir o conmover a través de un relato oral. Cuentan anécdotas con expresión y ritmo.", "materiales": ["Ninguno"], "grado": "4°" },
    { "area": "Fluidez", "nivel": 3, "nombre": "Improvisaciones (fluidez)", "duracion": 15, "descripcion": "Los alumnos improvisan diálogos a partir de situaciones dadas, trabajando la expresividad, el volumen y la claridad al hablar.", "materiales": ["Tarjetas con situaciones"], "grado": "5°" },
    { "area": "Fluidez", "nivel": 3, "nombre": "El cuento de todos", "duracion": 15, "descripcion": "El grupo crea una historia colectiva. Cada niño añade un segmento, manteniendo coherencia y usando diferentes voces y ritmos.", "materiales": ["Objeto para pasar como estafeta"], "grado": "5°" },
    { "area": "Fluidez", "nivel": 3, "nombre": "La hora de las noticias", "duracion": 15, "descripcion": "Los alumnos narran noticias de forma oral, practicando la fluidez, la entonación y la claridad al hablar en público.", "materiales": ["Periódicos", "Noticias"], "grado": "5°" },
    { "area": "Fluidez", "nivel": 3, "nombre": "El capítulo de hoy", "duracion": 15, "descripcion": "Lectura en voz alta de una novela por episodios. Se trabaja la fluidez y la comprensión a través de la lectura compartida.", "materiales": ["Novela infantil o juvenil"], "grado": "6°" },
    { "area": "Fluidez", "nivel": 3, "nombre": "El noticiero (fluidez)", "duracion": 15, "descripcion": "Los alumnos preparan y presentan un noticiero, practicando la dicción, entonación y fluidez al narrar noticias.", "materiales": ["Periódicos", "Micrófono de juguete"], "grado": "6°" },
    { "area": "Fluidez", "nivel": 3, "nombre": "Situaciones cotidianas", "duracion": 15, "descripcion": "Los alumnos dramatizan situaciones cotidianas, trabajando la expresividad del cuerpo y la voz, y la fluidez en el diálogo.", "materiales": ["Ninguno"], "grado": "6°" },

    // ------------------------------------------------------------
    // PRECISIÓN — NIVEL 1
    // ------------------------------------------------------------
    { "area": "Precisión", "nivel": 1, "nombre": "Cazador de sílabas", "duracion": 5, "descripcion": "El alumno palmea las sílabas de una palabra (ej. Ma-ri-po-sa) y busca otras con el mismo número de sílabas.", "materiales": ["Tarjetas de palabras con dibujos"], "grado": "1°" },
    { "area": "Precisión", "nivel": 1, "nombre": "Separa y lee", "duracion": 5, "descripcion": "El docente escribe palabras compuestas sin separación (ej. sacacorchos) y el alumno debe dividirlas en dos palabras.", "materiales": ["Pizarra", "Marcador"], "grado": "1°" },
    { "area": "Precisión", "nivel": 1, "nombre": "Relaciona imagen y palabra", "duracion": 10, "descripcion": "Se presentan tarjetas con imágenes y tarjetas con nombres. El alumno debe unir cada imagen con su palabra correspondiente.", "materiales": ["Tarjetas de imágenes", "Tarjetas con palabras"], "grado": "1°" },
    { "area": "Precisión", "nivel": 1, "nombre": "El sobre de palabras", "duracion": 10, "descripcion": "El alumno elige palabras, el docente las escribe en tarjetas y las guarda en un sobre. Se usan para clasificarlas y leerlas.", "materiales": ["Sobre tamaño carta", "Tarjetas de cartoncillo"], "grado": "1°" },
    { "area": "Precisión", "nivel": 1, "nombre": "El trabajo con el nombre propio", "duracion": 10, "descripcion": "El alumno identifica y escribe su nombre entre los de sus compañeros. Se trabaja la estabilidad de la representación escrita.", "materiales": ["Tarjetas con nombres", "Lista de asistencia"], "grado": "1°" },
    { "area": "Precisión", "nivel": 1, "nombre": "El detective de letras", "duracion": 5, "descripcion": "El docente escribe una palabra en el pizarrón (ej. 'gato') y pide a los alumnos que busquen una letra específica (ej. '¿Dónde está la 'a'?'). El alumno pasa al pizarrón y señala la letra. Luego, entre todos, cuentan cuántas veces aparece esa letra en la palabra. Se repite con 3-4 palabras.", "materiales": ["Pizarrón", "Marcador"], "grado": "1°" },
    { "area": "Precisión", "nivel": 1, "nombre": "El memorama de imágenes y palabras", "duracion": 10, "descripcion": "El docente prepara un memorama con 6 pares (imagen-palabra). Los alumnos, en parejas, juegan a encontrar los pares. Cuando encuentran una imagen, deben decir la palabra y buscarla escrita. El docente apoya a quienes tienen dificultad.", "materiales": ["Memorama casero (6 pares imagen-palabra)"], "grado": "1°" },
    { "area": "Precisión", "nivel": 1, "nombre": "El bingo de sílabas", "duracion": 10, "descripcion": "El docente prepara tarjetas de bingo con sílabas (ma, me, mi, mo, mu, pa, pe, pi, po, pu). Dice una sílaba en voz alta y los alumnos buscan la sílaba en sus tarjetas. Cuando completan su tarjeta, dicen '¡Bingo!' y leen todas las sílabas.", "materiales": ["Tarjetas de bingo con sílabas", "Fichas para marcar"], "grado": "1°" },
    { "area": "Precisión", "nivel": 1, "nombre": "La lotería de palabras", "duracion": 10, "descripcion": "El docente prepara tablas de lotería con palabras cortas (sol, luna, flor, gato, casa, pez, etc.). Muestra una tarjeta con la palabra escrita y la lee en voz alta. Los alumnos buscan la palabra en su tabla y la marcan. El docente apoya a los alumnos que tienen dificultad para encontrarla.", "materiales": ["Tablas de lotería (4x4)", "Tarjetas con palabras", "Fichas"], "grado": "1°" },
    { "area": "Precisión", "nivel": 1, "nombre": "El rompecabezas de la palabra", "duracion": 10, "descripcion": "El docente prepara rompecabezas de palabras: escribe una palabra, la recorta en sílabas y la mete en un sobre. El alumno debe ordenar las sílabas para formar la palabra. Se repite con 4-5 palabras diferentes.", "materiales": ["Sobres con sílabas recortadas de palabras (4-5 palabras)"], "grado": "1°" },
    { "area": "Precisión", "nivel": 1, "nombre": "El semáforo de la escritura", "duracion": 10, "descripcion": "El docente dice una palabra y los alumnos la escriben en sus pizarras individuales. Cuando terminan, levantan su pizarra. Si está bien, se pone un círculo verde. Si tiene errores, se pone un círculo amarillo y el docente apoya al alumno a corregir. Se repite con 5-6 palabras.", "materiales": ["Pizarras individuales (o pizarrón de mano)", "Marcadores", "Tarjetas verdes y amarillas"], "grado": "1°" },
    { "area": "Precisión", "nivel": 1, "nombre": "El carrusel de palabras en familia", "duracion": 10, "descripcion": "El docente forma equipos de 3. Cada equipo recibe una tarjeta con una palabra (ej. 'pan'). Deben escribir todas las palabras que se les ocurran que empiecen igual (pato, pala, perro, etc.). Luego rotan las tarjetas entre equipos y agregan más palabras. Al final, leen todas las palabras.", "materiales": ["Tarjetas con palabras iniciales (5-6)", "Hojas para escribir"], "grado": "1°" },
    { "area": "Precisión", "nivel": 1, "nombre": "El dominó de rimas", "duracion": 10, "descripcion": "El docente prepara un dominó con palabras que riman (sol-col, flor-dolor, etc.). Los alumnos, en parejas, juegan a unir las palabras que riman. Cuando unen dos palabras, deben leerlas en voz alta. El docente apoya a quienes tienen dificultad.", "materiales": ["Fichas de dominó con palabras que riman"], "grado": "1°" },
    { "area": "Precisión", "nivel": 1, "nombre": "Mi nombre secreto", "duracion": 10, "descripcion": "El docente escribe el nombre de cada alumno en una tarjeta y la coloca boca abajo. Cada alumno toma una tarjeta al azar y debe identificar si es su nombre. Si no lo es, busca a su dueño y se lo entrega. Luego, cada alumno escribe su nombre en su cuaderno.", "materiales": ["Tarjetas con nombres de los alumnos"], "grado": "1°" },

    // ------------------------------------------------------------
    // PRECISIÓN — NIVEL 2
    // ------------------------------------------------------------
    { "area": "Precisión", "nivel": 2, "nombre": "El intruso (precisión)", "duracion": 10, "descripcion": "Se presenta una lista de palabras donde 4 comparten una característica (riman, misma sílaba inicial) y una no. El alumno identifica la intrusa.", "materiales": ["Listados impresos de palabras", "Lápiz"], "grado": "2°" },
    { "area": "Precisión", "nivel": 2, "nombre": "Palabras trampa (pares mínimos)", "duracion": 10, "descripcion": "El docente dice pares de palabras que se diferencian por una letra (pera/perra, casa/caza). El alumno escribe la palabra y la usa en una frase.", "materiales": ["Listado de pares mínimos", "Cuaderno"], "grado": "2°" },
    { "area": "Precisión", "nivel": 2, "nombre": "Completa la palabra (letra final)", "duracion": 10, "descripcion": "Se presenta una imagen y su palabra escrita con la última letra faltante. El alumno identifica y escribe la letra que falta.", "materiales": ["Tarjetas con imágenes y palabras incompletas", "Lápiz"], "grado": "2°" },
    { "area": "Precisión", "nivel": 2, "nombre": "Rompecabezas de sílabas", "duracion": 10, "descripcion": "El alumno recibe tarjetas con palabras divididas en sílabas desordenadas. Debe armarlas para formar la palabra correcta.", "materiales": ["Tarjetas con sílabas de varias palabras"], "grado": "2°" },
    { "area": "Precisión", "nivel": 2, "nombre": "¿Con cuáles letras se escribe?", "duracion": 10, "descripcion": "El alumno escribe listas de palabras (frutas, útiles) apoyándose en preguntas del docente sobre las letras que las componen.", "materiales": ["Pizarra", "Cuaderno"], "grado": "2°" },
    { "area": "Precisión", "nivel": 2, "nombre": "La tiendita", "duracion": 15, "descripcion": "Los alumnos juegan a la tiendita, escriben listas de productos, precios y letreros. Se trabaja la escritura con valor sonoro convencional.", "materiales": ["Envolturas de productos", "Hojas", "Lápices"], "grado": "2°" },
    { "area": "Precisión", "nivel": 2, "nombre": "Las cartas", "duracion": 15, "descripcion": "Los alumnos escriben cartas a compañeros de otro grupo, practicando la escritura y la segmentación de palabras.", "materiales": ["Hojas", "Sobres", "Lápices"], "grado": "2°" },
    { "area": "Precisión", "nivel": 2, "nombre": "El grafómetro", "duracion": 15, "descripcion": "Los alumnos usan un grafómetro para formar palabras y analizar su escritura (mayúsculas, minúsculas, letras).", "materiales": ["Grafómetro", "Letras móviles"], "grado": "1°" },
    { "area": "Precisión", "nivel": 2, "nombre": "¡Lotería! (1°)", "duracion": 15, "descripcion": "Los alumnos juegan a la lotería con palabras del tarjetero, avanzando en la comprensión del sistema de escritura.", "materiales": ["Tablas de lotería con palabras", "Tarjetas con palabras", "Fichas"], "grado": "1°" },

    // ------------------------------------------------------------
    // PRECISIÓN — NIVEL 3
    // ------------------------------------------------------------
    { "area": "Precisión", "nivel": 3, "nombre": "Acentuación detectivesca", "duracion": 15, "descripcion": "Se entrega un texto sin tildes. El alumno debe colocar las tildes que faltan y leer el texto respetando la correcta acentuación.", "materiales": ["Texto sin tildes", "Bolígrafo rojo"], "grado": "3°" },
    { "area": "Precisión", "nivel": 3, "nombre": "Crucigramas (precisión)", "duracion": 15, "descripcion": "El alumno resuelve un crucigrama con palabras que contienen sílabas con dificultades ortográficas (gue/gui, ce/ci, etc.).", "materiales": ["Crucigrama impreso", "Lápiz"], "grado": "3°" },
    { "area": "Precisión", "nivel": 3, "nombre": "El ahorcado (precisión)", "duracion": 15, "descripcion": "Juego del ahorcado con palabras que presentan dificultades ortográficas específicas. Los alumnos deben adivinar la palabra letra por letra.", "materiales": ["Pizarrón", "Marcador"], "grado": "3°" },
    { "area": "Precisión", "nivel": 3, "nombre": "Descubre la regla (4°)", "duracion": 15, "descripcion": "Los alumnos identifican regularidades en el uso de la 'b' y deducen una regla ortográfica a partir de ejemplos.", "materiales": ["Pizarrón", "Diccionario"], "grado": "4°" },
    { "area": "Precisión", "nivel": 3, "nombre": "El ahorcado (4°)", "duracion": 15, "descripcion": "Juego del ahorcado para trabajar la convencionalidad ortográfica con palabras que comparten una misma dificultad ortográfica.", "materiales": ["Pizarrón", "Tarjetas con palabras"], "grado": "4°" },
    { "area": "Precisión", "nivel": 3, "nombre": "¿Cuál es la regla? (5°)", "duracion": 15, "descripcion": "Los alumnos identifican regularidades en el uso de la 'b' y deducen una regla ortográfica a partir de ejemplos.", "materiales": ["Pizarrón", "Diccionario"], "grado": "5°" },
    { "area": "Precisión", "nivel": 3, "nombre": "Para mejorar la ortografía (5°)", "duracion": 15, "descripcion": "Estrategias para mejorar la ortografía: identificación de errores en textos, uso de diccionario y deducción de reglas.", "materiales": ["Textos con errores", "Diccionario", "Cuaderno"], "grado": "5°" },
    { "area": "Precisión", "nivel": 3, "nombre": "Descubre la regla (6°)", "duracion": 15, "descripcion": "Los alumnos identifican regularidades en el uso de la 'z' y deducen una regla ortográfica a partir de ejemplos.", "materiales": ["Pizarrón", "Diccionario"], "grado": "6°" },
    { "area": "Precisión", "nivel": 3, "nombre": "Otros usos de la coma", "duracion": 15, "descripcion": "Los alumnos identifican el uso de la coma en frases explicativas y aposiciones, y practican su uso en la escritura.", "materiales": ["Textos con comas", "Pizarrón", "Cuaderno"], "grado": "6°" },

    // ------------------------------------------------------------
    // ATENCIÓN A PALABRAS COMPLEJAS — NIVEL 1
    // ------------------------------------------------------------
    { "area": "Atención a palabras complejas", "nivel": 1, "nombre": "Subraya la palabra", "duracion": 5, "descripcion": "Se entrega un texto con palabras destacadas en negrita (ej. 'había', 'excepción'). El alumno solo debe leer esas palabras en voz alta.", "materiales": ["Texto con palabras clave en negrita"], "grado": "1°" },
    { "area": "Atención a palabras complejas", "nivel": 1, "nombre": "Memoria visual", "duracion": 5, "descripcion": "Se muestra una palabra compleja (ej. 'ferrocarril') durante 3 segundos. Luego se oculta y el alumno la escribe de memoria.", "materiales": ["Tarjetas de palabras complejas", "Pizarra individual"], "grado": "1°" },
    { "area": "Atención a palabras complejas", "nivel": 1, "nombre": "La letra H (1°)", "duracion": 10, "descripcion": "El alumno identifica palabras con H en un texto y reflexiona sobre por qué no tiene sonido. Se escriben listas de palabras con H.", "materiales": ["Texto con muchas H", "Marcadores", "Pizarrón"], "grado": "1°" },
    { "area": "Atención a palabras complejas", "nivel": 1, "nombre": "El cazador de la letra misteriosa", "duracion": 5, "descripcion": "El docente elige una letra compleja (ej. 'ñ', 'rr', 'll', 'h', 'c' con sonido /k/). Muestra una tarjeta con esa letra y pide a los alumnos que busquen en un texto (o en la biblioteca del aula) palabras que contengan esa letra. Cada alumno encuentra una palabra, la escribe en su cuaderno y la comparte con el grupo.", "materiales": ["Tarjetas con letras complejas", "Textos variados (libros, revistas)"], "grado": "1°" },
    { "area": "Atención a palabras complejas", "nivel": 1, "nombre": "El sobre de las palabras con trampa", "duracion": 5, "descripcion": "El docente prepara un sobre con 5 tarjetas que tienen palabras con una dificultad ortográfica (ej. 'hermano', 'lluvia', 'guitarra', 'niño', 'silla'). Cada alumno toma una tarjeta, la observa, la deletrea en voz alta con el apoyo del docente y la escribe en su cuaderno. Luego, la coloca en la 'caja de palabras con trampa'.", "materiales": ["Sobre con tarjetas (5 palabras)", "Caja", "Cuaderno"], "grado": "1°" },
    { "area": "Atención a palabras complejas", "nivel": 1, "nombre": "La sopa de letras fácil", "duracion": 10, "descripcion": "El docente prepara una sopa de letras muy sencilla con palabras de alta frecuencia que contengan letras complejas (ej. 'gato', 'niña', 'huevo', 'llave'). Los alumnos buscan las palabras y las encierran en un círculo. Luego, las escriben en su cuaderno.", "materiales": ["Sopa de letras sencilla", "Lápices de colores"], "grado": "1°" },
    { "area": "Atención a palabras complejas", "nivel": 1, "nombre": "Las palabras gemelas", "duracion": 10, "descripcion": "El docente escribe un par de palabras que se parecen (cara/casa, pera/perra). Los alumnos observan las palabras, señalan la diferencia y la dicen en voz alta. Luego, las escriben en su cuaderno y dibujan el objeto que representan.", "materiales": ["Pizarrón", "Tarjetas con palabras parecidas (4-5 pares)"], "grado": "1°" },
    { "area": "Atención a palabras complejas", "nivel": 1, "nombre": "El cartel de las palabras con H", "duracion": 10, "descripcion": "El docente presenta tarjetas con imágenes de objetos que empiezan con H (huevo, hoja, hilo, higo). Los alumnos dicen el nombre de cada objeto, lo escriben en una tarjeta con ayuda del docente y lo pegan junto a la imagen en un cartel. El cartel se coloca en el salón.", "materiales": ["Imágenes (huevo, hoja, hilo, higo)", "Tarjetas", "Pegamento", "Cartulina"], "grado": "1°" },
    { "area": "Atención a palabras complejas", "nivel": 1, "nombre": "El llavero de palabras difíciles", "duracion": 5, "descripcion": "El docente prepara un llavero con 5 tarjetas. Cada tarjeta tiene una palabra compleja (ej. 'lluvia', 'guitarra', 'hormiga', 'niña'). Cada día se trabaja una palabra: se observa, se deletrea, se escribe y se usa en una oración. Al final de la semana, el alumno se lleva el llavero a casa para practicar.", "materiales": ["Llavero con tarjetas de palabras (5)", "Cuaderno"], "grado": "1°" },
    { "area": "Atención a palabras complejas", "nivel": 1, "nombre": "El juego de los opuestos visuales", "duracion": 5, "descripcion": "El docente escribe una palabra con una letra compleja (ej. 'lluvia') y su opuesto sin esa letra (ej. 'sol'). Los alumnos observan ambas palabras, identifican la letra diferente y la señalan. Luego, las escriben en su cuaderno.", "materiales": ["Pizarrón", "Lista de pares opuestos (4-5)"], "grado": "1°" },
    { "area": "Atención a palabras complejas", "nivel": 1, "nombre": "El dominó de palabras con sílabas complejas", "duracion": 10, "descripcion": "El docente prepara un dominó con palabras que contienen sílabas complejas (ej. 'bra', 'cla', 'fla', 'glo'). Los alumnos, en parejas, juegan a unir las palabras que tienen la misma sílaba compleja. Cuando unen dos palabras, las leen en voz alta.", "materiales": ["Fichas de dominó con sílabas complejas"], "grado": "2°" },

    // ------------------------------------------------------------
    // ATENCIÓN A PALABRAS COMPLEJAS — NIVEL 2
    // ------------------------------------------------------------
    { "area": "Atención a palabras complejas", "nivel": 2, "nombre": "Palabras trampa (atención)", "duracion": 10, "descripcion": "El docente dice pares de palabras que se diferencian por una letra (casa/caza, carro/caro). El alumno escribe y usa en frases.", "materiales": ["Listado de pares mínimos", "Cuaderno"], "grado": "2°" },
    { "area": "Atención a palabras complejas", "nivel": 2, "nombre": "Lectura con lupa", "duracion": 10, "descripcion": "Se entrega un texto con palabras complejas resaltadas. El alumno lee y, al llegar a esas palabras, las descompone en sílabas.", "materiales": ["Texto resaltado", "Lupa de cartón (opcional)"], "grado": "2°" },
    { "area": "Atención a palabras complejas", "nivel": 2, "nombre": "¡Cambia una letra!", "duracion": 10, "descripcion": "El docente escribe una palabra y los alumnos deben cambiarla, modificando una sola letra, para formar una palabra nueva.", "materiales": ["Pizarrón", "Marcador"], "grado": "2°" },
    { "area": "Atención a palabras complejas", "nivel": 2, "nombre": "¿Cómo adivinas? (2°)", "duracion": 15, "descripcion": "Los niños reflexionan sobre el juego del lenguaje involucrado en la creación y solución de adivinanzas.", "materiales": ["Libros que presenten adivinanzas"], "grado": "2°" },
    { "area": "Atención a palabras complejas", "nivel": 2, "nombre": "Aparece y desaparece (prefijos)", "duracion": 15, "descripcion": "Los alumnos agregan prefijos a palabras para formar antónimos y reflexionan sobre el cambio de significado.", "materiales": ["Pizarrón", "Cuaderno"], "grado": "3°" },

    // ------------------------------------------------------------
    // ATENCIÓN A PALABRAS COMPLEJAS — NIVEL 3
    // ------------------------------------------------------------
    { "area": "Atención a palabras complejas", "nivel": 3, "nombre": "Análisis morfológico exprés", "duracion": 15, "descripcion": "El alumno lee un párrafo y subraya prefijos y sufijos (ej. 'inútil', 'felicidad'), explicando cómo cambia el significado de la raíz.", "materiales": ["Párrafo con palabras derivadas", "Marcador"], "grado": "3°" },
    { "area": "Atención a palabras complejas", "nivel": 3, "nombre": "Uso de prefijos en antónimos (5°)", "duracion": 15, "descripcion": "Los alumnos identifican y utilizan prefijos que indican negación (in-, des-, a-) para formar antónimos y crear definiciones.", "materiales": ["Pizarrón", "Diccionario"], "grado": "4°" },
    { "area": "Atención a palabras complejas", "nivel": 3, "nombre": "Para ampliar el vocabulario (5°)", "duracion": 15, "descripcion": "Los alumnos conocen y utilizan distintas estrategias para ampliar su vocabulario: contexto, diccionario, sinónimos, antónimos, redes de palabras.", "materiales": ["Diccionario", "Cuaderno", "Textos variados"], "grado": "5°" },
    { "area": "Atención a palabras complejas", "nivel": 3, "nombre": "Inventa palabras (6°)", "duracion": 15, "descripcion": "Los alumnos conocen el significado de prefijos que indican proporción o tamaño (micro, mini, macro, super, ultra) y los utilizan.", "materiales": ["Pizarrón", "Diccionario"], "grado": "6°" },
    { "area": "Atención a palabras complejas", "nivel": 3, "nombre": "Sentido figurado", "duracion": 15, "descripcion": "Los alumnos identifican y comprenden el lenguaje figurado en textos literarios y cotidianos, ampliando su vocabulario.", "materiales": ["Poemas", "Refranes", "Cuaderno"], "grado": "6°" },

    // ------------------------------------------------------------
    // USO DE LA VOZ — NIVEL 1
    // ------------------------------------------------------------
    { "area": "Uso de la voz", "nivel": 1, "nombre": "Respiración de globo", "duracion": 5, "descripcion": "Ejercicio de respiración: inflar un globo al inspirar y desinflarlo al espirar diciendo 'sssss'. Luego leer una frase con el aire controlado.", "materiales": ["Ninguno (imaginería)"], "grado": "1°" },
    { "area": "Uso de la voz", "nivel": 1, "nombre": "El teléfono descompuesto (voz)", "duracion": 5, "descripcion": "Los alumnos se sientan en fila. El primero susurra una palabra al oído del siguiente. Se trabaja la claridad al hablar.", "materiales": ["Ninguno"], "grado": "1°" },
    { "area": "Uso de la voz", "nivel": 1, "nombre": "La caja de los sonidos mágicos", "duracion": 5, "descripcion": "El docente prepara una caja con tarjetas que tienen onomatopeyas (¡pum!, ¡zas!, ¡clic!, ¡muu!, ¡guau!). Cada alumno saca una tarjeta, la lee en voz alta imitando el sonido. El grupo adivina qué sonido es. Se repite con 4-5 alumnos.", "materiales": ["Caja", "Tarjetas con onomatopeyas"], "grado": "1°" },
    { "area": "Uso de la voz", "nivel": 1, "nombre": "El eco de emociones", "duracion": 5, "descripcion": "El docente dice una palabra con una emoción específica (alegre, triste, enojado, asustado). Los alumnos repiten la palabra imitando la emoción. Luego, el docente muestra tarjetas con emociones y los alumnos dicen una palabra con la emoción indicada.", "materiales": ["Tarjetas con emociones (alegría, tristeza, enojo, miedo)", "Lista de palabras cortas"], "grado": "1°" },
    { "area": "Uso de la voz", "nivel": 1, "nombre": "El globo de la respiración", "duracion": 5, "descripcion": "El docente da a cada alumno un globo desinflado. Los alumnos inflan el globo mientras inspiran profundamente, y lo desinflan mientras espiran lentamente diciendo 'sssss'. Luego, repiten el ejercicio sin globo y leen una frase corta con el aire controlado.", "materiales": ["Globos"], "grado": "1°" },
    { "area": "Uso de la voz", "nivel": 1, "nombre": "El semáforo del volumen", "duracion": 5, "descripcion": "El docente muestra tarjetas de colores: verde (voz alta), amarillo (voz media) y rojo (voz baja). Los alumnos leen una frase corta con el volumen indicado por el color. Se alternan los colores para practicar diferentes volúmenes.", "materiales": ["Tarjetas de colores (verde, amarillo, rojo)", "Frase corta"], "grado": "1°" },
    { "area": "Uso de la voz", "nivel": 1, "nombre": "La máquina de las voces divertidas", "duracion": 5, "descripcion": "El docente prepara tarjetas con personajes (robot, abuelita, niño pequeño, monstruo, cantante). Cada alumno toma una tarjeta y debe leer una frase corta imitando la voz del personaje. El grupo adivina qué personaje es.", "materiales": ["Tarjetas con personajes", "Lista de frases cortas"], "grado": "1°" },
    { "area": "Uso de la voz", "nivel": 1, "nombre": "El micrófono de la confianza", "duracion": 5, "descripcion": "El docente usa un micrófono de juguete. Cada alumno pasa al frente, sostiene el micrófono y dice una palabra o frase corta que el docente le sugiere. El micrófono ayuda a dar confianza y a escucharse mejor.", "materiales": ["Micrófono de juguete", "Lista de palabras/frases"], "grado": "1°" },
    { "area": "Uso de la voz", "nivel": 1, "nombre": "El juego del teléfono descompuesto con vocales", "duracion": 5, "descripcion": "Los alumnos se sientan en círculo. El docente susurra una palabra al oído del primer alumno. Este la susurra al siguiente, y así sucesivamente. Al final, se compara la palabra final con la original. Se trabaja la claridad al hablar.", "materiales": ["Lista de palabras cortas"], "grado": "1°" },
    { "area": "Uso de la voz", "nivel": 1, "nombre": "El canto de las vocales", "duracion": 5, "descripcion": "El docente canta las vocales con diferentes tonos (agudo, grave). Los alumnos repiten cada vocal imitando el tono. Luego, repiten palabras cortas con diferentes tonos. Se practica el control de la voz.", "materiales": ["Ninguno"], "grado": "1°" },

    // ------------------------------------------------------------
    // USO DE LA VOZ — NIVEL 2
    // ------------------------------------------------------------
    { "area": "Uso de la voz", "nivel": 2, "nombre": "Modulación de emociones (voz)", "duracion": 10, "descripcion": "Se entrega una misma oración y el alumno debe leerla con tono de: alegría, tristeza, sorpresa y enojo.", "materiales": ["Tarjetas de emociones", "Frase modelo"], "grado": "2°" },
    { "area": "Uso de la voz", "nivel": 2, "nombre": "Yo, el locutor", "duracion": 10, "descripcion": "El alumno lee una noticia corta imitando la voz de un locutor de radio o televisión, cuidando el volumen y la claridad.", "materiales": ["Noticia corta", "Micrófono de juguete"], "grado": "2°" },
    { "area": "Uso de la voz", "nivel": 2, "nombre": "El viento y el trueno", "duracion": 10, "descripcion": "Se practica el volumen. Para un texto sobre una tormenta, el alumno usa voz suave (viento) y voz fuerte (trueno).", "materiales": ["Texto con elementos de volumen"], "grado": "2°" },

    // ------------------------------------------------------------
    // USO DE LA VOZ — NIVEL 3
    // ------------------------------------------------------------
    { "area": "Uso de la voz", "nivel": 3, "nombre": "Locución de noticias", "duracion": 15, "descripcion": "El alumno lee una noticia como locutor de radio, cuidando el volumen, las pausas y la entonación. Se graba y se autoevalúa.", "materiales": ["Noticia corta", "Grabadora (celular)"], "grado": "3°" },
    { "area": "Uso de la voz", "nivel": 3, "nombre": "Teatro de voces (voz)", "duracion": 15, "descripcion": "Se asigna un personaje a cada alumno. Leen un diálogo poniendo énfasis en la expresividad, velocidad y volumen según el personaje.", "materiales": ["Guión de diálogo", "Tarjetas de personajes"], "grado": "3°" },
    { "area": "Uso de la voz", "nivel": 3, "nombre": "Poesía con efectos de sonido", "duracion": 15, "descripcion": "Se prepara una poesía coral que incluye efectos de sonido con la voz (susurros, ecos, onomatopeyas) para dar mayor expresividad.", "materiales": ["Poema", "Instrumentos de percusión"], "grado": "4°" },
    { "area": "Uso de la voz", "nivel": 3, "nombre": "El debate (voz)", "duracion": 15, "descripcion": "Se organiza un debate sobre un tema de interés. Los alumnos expresan argumentos con claridad, volumen adecuado y tono persuasivo.", "materiales": ["Tema de debate", "Tarjetas para argumentos"], "grado": "4°" },
    { "area": "Uso de la voz", "nivel": 3, "nombre": "Pido la palabra", "duracion": 15, "descripcion": "Se organiza una asamblea donde los alumnos expresan opiniones, críticas y propuestas, practicando el respeto de turnos y la claridad.", "materiales": ["Ninguno"], "grado": "5°" },
    { "area": "Uso de la voz", "nivel": 3, "nombre": "Improvisaciones (voz)", "duracion": 15, "descripcion": "Los alumnos improvisan diálogos a partir de situaciones dadas, trabajando la expresividad del cuerpo y la voz.", "materiales": ["Tarjetas con situaciones"], "grado": "5°" },
    { "area": "Uso de la voz", "nivel": 3, "nombre": "Quiero preguntarte", "duracion": 15, "descripcion": "Los alumnos participan en entrevistas colectivas, expresando puntos de vista y respondiendo preguntas sobre temas de interés personal.", "materiales": ["Ninguno"], "grado": "6°" },
    { "area": "Uso de la voz", "nivel": 3, "nombre": "Esta noche en el estudio...", "duracion": 15, "descripcion": "Los alumnos preparan y representan una entrevista formal, trabajando el uso de lenguaje formal y la expresividad oral.", "materiales": ["Guión de entrevista", "Grabadora"], "grado": "6°" },

    // ------------------------------------------------------------
    // SEGURIDAD Y DISPOSICIÓN — NIVEL 1
    // ------------------------------------------------------------
    { "area": "Seguridad y disposición", "nivel": 1, "nombre": "Ritual de inicio", "duracion": 5, "descripcion": "Antes de leer, el alumno se sienta recto, respira profundo y dice: 'Estoy listo para leer'. Activa su disposición.", "materiales": ["Ninguno"], "grado": "1°" },
    { "area": "Seguridad y disposición", "nivel": 1, "nombre": "El espejo positivo", "duracion": 5, "descripcion": "El alumno se mira en un espejo pequeño mientras se dice a sí mismo: 'Soy un buen lector' y lee una frase corta mirándose a los ojos.", "materiales": ["Espejo pequeño"], "grado": "1°" },
    { "area": "Seguridad y disposición", "nivel": 1, "nombre": "¿Qué puedo leer?", "duracion": 5, "descripcion": "Exploración libre de la biblioteca del aula. Cada alumno elige un libro que le llame la atención, solo por su portada o título.", "materiales": ["Libros de la biblioteca del aula"], "grado": "1°" },
    { "area": "Seguridad y disposición", "nivel": 1, "nombre": "Lectura en voz baja para mí", "duracion": 5, "descripcion": "Se pide a los alumnos que lean en voz baja o susurrada un texto corto, sin la presión de un público.", "materiales": ["Texto corto para cada alumno"], "grado": "1°" },
    { "area": "Seguridad y disposición", "nivel": 1, "nombre": "El espejo del lector valiente", "duracion": 5, "descripcion": "El docente coloca un espejo grande en el salón. Cada alumno pasa frente al espejo, se mira a los ojos, sonríe y dice: '¡Yo soy un gran lector!' o '¡Yo puedo leer!'. Luego lee una palabra corta mirándose al espejo.", "materiales": ["Espejo grande"], "grado": "1°" },
    { "area": "Seguridad y disposición", "nivel": 1, "nombre": "La corona de los lectores", "duracion": 5, "descripcion": "El docente prepara una corona de cartón. Cada día, un alumno se convierte en 'el rey o reina de la lectura'. Usa la corona durante la sesión y lee una frase o palabra con el apoyo del docente. Al final, recibe un aplauso.", "materiales": ["Corona de cartón decorada"], "grado": "1°" },
    { "area": "Seguridad y disposición", "nivel": 1, "nombre": "El semáforo de las emociones (disposición)", "duracion": 5, "descripcion": "El docente muestra tarjetas de colores: verde (me siento listo), amarillo (me siento nervioso) y rojo (no me siento listo). Cada alumno elige una tarjeta y la coloca en su escritorio. El docente comenta con cada alumno cómo se siente y le ofrece apoyo.", "materiales": ["Tarjetas de colores (verde, amarillo, rojo)"], "grado": "1°" },
    { "area": "Seguridad y disposición", "nivel": 1, "nombre": "La caja de los logros lectores", "duracion": 10, "descripcion": "El docente prepara una caja decorada con la palabra 'Logros'. Cada vez que un alumno lee una palabra nueva o mejora en su lectura, escribe su logro en una tarjeta y la deposita en la caja. Al final de la semana, se leen algunos logros y se celebran.", "materiales": ["Caja decorada", "Tarjetas", "Lápices de colores"], "grado": "1°" },
    { "area": "Seguridad y disposición", "nivel": 1, "nombre": "El cartel de los lectores comprometidos", "duracion": 10, "descripcion": "El docente prepara un cartel con los nombres de los alumnos y una lista de 'compromisos' (ej. 'leer 5 minutos en casa', 'practicar una palabra nueva'). Cada alumno elige un compromiso y lo coloca junto a su nombre. Al final de la semana, se revisan los compromisos cumplidos.", "materiales": ["Cartel", "Tarjetas con compromisos", "Marcadores"], "grado": "2°" },
    { "area": "Seguridad y disposición", "nivel": 1, "nombre": "El abrazo del lector", "duracion": 5, "descripcion": "El docente y los alumnos se dan un abrazo (o un saludo especial) al inicio de la sesión de lectura, con la frase: '¡Hoy vamos a leer y lo vamos a disfrutar!'. Esto crea un ambiente de confianza y seguridad.", "materiales": ["Ninguno"], "grado": "1°" },
    { "area": "Seguridad y disposición", "nivel": 1, "nombre": "El estuche de los miedos", "duracion": 10, "descripcion": "El docente prepara un estuche o caja pequeña. Cada alumno escribe en una tarjeta un miedo que tenga al leer (ej. 'me da pena', 'no quiero equivocarme'). Las depositan en el estuche. El docente las lee y el grupo comenta cómo superar esos miedos.", "materiales": ["Estuche o caja pequeña", "Tarjetas", "Lápices"], "grado": "2°" },
    { "area": "Seguridad y disposición", "nivel": 1, "nombre": "El cuento de los lectores valientes", "duracion": 10, "descripcion": "El docente inventa un cuento donde los personajes son los alumnos y el reto es leer un texto. El cuento destaca el valor, el esfuerzo y la alegría de leer. Los alumnos dibujan una escena del cuento.", "materiales": ["Cuento inventado", "Hojas para dibujo", "Colores"], "grado": "1°" },
    { "area": "Seguridad y disposición", "nivel": 1, "nombre": "El podio de los lectores", "duracion": 10, "descripcion": "El docente prepara un 'podio' con tres niveles (cartón o cajas). Cada alumno sube al podio (el que se sienta más seguro) para leer una palabra o frase. Se celebra cada intento con aplausos. Se busca que todos los alumnos suban al menos al primer nivel.", "materiales": ["Cartón o cajas para podio", "Tarjetas con palabras/frases"], "grado": "1°" },

    // ------------------------------------------------------------
    // SEGURIDAD Y DISPOSICIÓN — NIVEL 2
    // ------------------------------------------------------------
    { "area": "Seguridad y disposición", "nivel": 2, "nombre": "Mis logros lectores", "duracion": 10, "descripcion": "El alumno lee un texto fácil y registra en su 'diario de lector' cuántas palabras leyó bien y qué hizo bien.", "materiales": ["Diario de lector", "Texto corto"], "grado": "2°" },
    { "area": "Seguridad y disposición", "nivel": 2, "nombre": "Aplausos por párrafo", "duracion": 10, "descripcion": "Por cada párrafo que el alumno lee sin errores, el grupo da una palmada. Se refuerza el esfuerzo y la atención sostenida.", "materiales": ["Texto por párrafos"], "grado": "2°" },
    { "area": "Seguridad y disposición", "nivel": 2, "nombre": "El lector recomendado", "duracion": 10, "descripcion": "Un alumno que ha leído un libro lo recomienda a sus compañeros, describiendo de qué trata y por qué le gustó.", "materiales": ["Libro leído previamente"], "grado": "2°" },
    { "area": "Seguridad y disposición", "nivel": 2, "nombre": "Un diario para todos (2°)", "duracion": 15, "descripcion": "Los alumnos establecen un diálogo por escrito en un diario del grupo, expresando ideas, sentimientos y opiniones.", "materiales": ["Cuaderno", "Lápices"], "grado": "2°" },
    { "area": "Seguridad y disposición", "nivel": 2, "nombre": "La biblioteca del salón (2°)", "duracion": 15, "descripcion": "Los alumnos participan en la organización de la biblioteca del aula: clasifican libros, elaboran etiquetas y establecen reglas.", "materiales": ["Libros", "Cartulinas", "Etiquetas", "Marcadores"], "grado": "2°" },

    // ------------------------------------------------------------
    // SEGURIDAD Y DISPOSICIÓN — NIVEL 3
    // ------------------------------------------------------------
    { "area": "Seguridad y disposición", "nivel": 3, "nombre": "Lectura en cámara lenta", "duracion": 15, "descripcion": "El alumno lee un texto desafiante extremadamente lento, enfocándose en cada palabra. El objetivo es la autoconfianza.", "materiales": ["Texto de nivel superior", "Cronómetro"], "grado": "3°" },
    { "area": "Seguridad y disposición", "nivel": 3, "nombre": "El club de los lectores", "duracion": 15, "descripcion": "Se reúne un grupo pequeño para comentar un libro que todos han leído. Cada alumno comparte su opinión sin ser evaluado.", "materiales": ["Libro leído en común"], "grado": "3°" },
    { "area": "Seguridad y disposición", "nivel": 3, "nombre": "Mi lectura favorita", "duracion": 15, "descripcion": "Cada alumno elige su texto favorito y lo lee al grupo, explicando por qué le gusta. Se celebra la diversidad de gustos.", "materiales": ["Texto elegido por el alumno"], "grado": "4°" },
    { "area": "Seguridad y disposición", "nivel": 3, "nombre": "El crítico literario", "duracion": 15, "descripcion": "El alumno escribe una breve reseña de un libro que ha leído, destacando lo que le gustó y lo que no. Comparte su reseña con el grupo.", "materiales": ["Libro leído", "Hoja para reseña"], "grado": "4°" },
    { "area": "Seguridad y disposición", "nivel": 3, "nombre": "Conozcámonos mejor", "duracion": 15, "descripcion": "Los niños se conocen mejor mediante conversación en parejas. Se trabaja la atención, el respeto de turnos y la escucha activa.", "materiales": ["Ninguno"], "grado": "5°" },
    { "area": "Seguridad y disposición", "nivel": 3, "nombre": "¿Para qué leer?", "duracion": 15, "descripcion": "Los niños comparten sus gustos y razones para leer. El maestro comparte sus propias lecturas. Se crea un espacio para compartir lecturas.", "materiales": ["Libros, periódicos, revistas variados"], "grado": "5°" },
    { "area": "Seguridad y disposición", "nivel": 3, "nombre": "Álbum de recuerdos", "duracion": 15, "descripcion": "Los alumnos utilizan la escritura como un medio para registrar acontecimientos y expresar sus emociones en el último año de primaria.", "materiales": ["Fotos", "Dibujos", "Hojas", "Carpeta"], "grado": "6°" },
    { "area": "Seguridad y disposición", "nivel": 3, "nombre": "Amigos para siempre", "duracion": 15, "descripcion": "Los alumnos escriben relatos expresando emociones y sentimientos hacia sus compañeros, fortaleciendo el vínculo grupal.", "materiales": ["Hojas", "Lápices de colores"], "grado": "6°" },

    // ------------------------------------------------------------
    // COMPRENSIÓN LECTORA — NIVEL 1
    // ------------------------------------------------------------
    { "area": "Comprensión lectora", "nivel": 1, "nombre": "Dibuja lo que lees", "duracion": 15, "descripcion": "El alumno lee una oración simple (ej. 'El perro corre bajo la lluvia') y hace un dibujo. Luego explica su dibujo a un compañero.", "materiales": ["Oraciones ilustrables", "Hojas en blanco", "Colores"], "grado": "1°" },
    { "area": "Comprensión lectora", "nivel": 1, "nombre": "Ordena la historia", "duracion": 10, "descripcion": "Se entregan 4 viñetas desordenadas de un cuento conocido. El alumno las ordena y cuenta la historia con sus palabras.", "materiales": ["Viñetas impresas", "Tijeras"], "grado": "1°" },
    { "area": "Comprensión lectora", "nivel": 1, "nombre": "¿Qué pasó primero?", "duracion": 10, "descripcion": "Se lee un cuento corto. Luego se muestran 3 dibujos de la historia y se pregunta cuál pasó primero, después y al final.", "materiales": ["Cuento corto", "Dibujos"], "grado": "1°" },
    { "area": "Comprensión lectora", "nivel": 1, "nombre": "El personaje favorito", "duracion": 10, "descripcion": "Después de una lectura, el alumno elige su personaje favorito y lo describe con sus palabras (cómo es, qué hace, por qué le gusta).", "materiales": ["Cuento leído"], "grado": "1°" },
    { "area": "Comprensión lectora", "nivel": 1, "nombre": "El cuento en dibujos", "duracion": 15, "descripcion": "El docente lee un cuento muy corto (3-4 oraciones) y muestra imágenes de cada parte. Los alumnos, después de escuchar el cuento, dibujan su parte favorita. Luego, ordenan las imágenes del cuento en secuencia (con ayuda del docente).", "materiales": ["Cuento corto", "Imágenes del cuento", "Hojas", "Colores"], "grado": "1°" },
    { "area": "Comprensión lectora", "nivel": 1, "nombre": "La caja de las preguntas fáciles", "duracion": 10, "descripcion": "El docente prepara una caja con tarjetas que tienen preguntas muy sencillas (ej. '¿Quién?', '¿Dónde?', '¿Qué?'). Después de leer un cuento, los alumnos toman una tarjeta y responden la pregunta sobre el cuento (con apoyo del docente).", "materiales": ["Caja", "Tarjetas con preguntas (¿Quién?, ¿Dónde?, ¿Qué?)", "Cuento"], "grado": "1°" },
    { "area": "Comprensión lectora", "nivel": 1, "nombre": "El cuento con imágenes para ordenar", "duracion": 10, "descripcion": "El docente entrega a los alumnos 4 imágenes desordenadas de un cuento. Los alumnos deben ordenarlas (primero, después, al final) con ayuda del docente. Luego, cuentan la historia en orden.", "materiales": ["Imágenes desordenadas de un cuento (4)"], "grado": "1°" },
    { "area": "Comprensión lectora", "nivel": 1, "nombre": "El mural de los personajes favoritos", "duracion": 15, "descripcion": "El docente lee un cuento. Después, cada alumno elige un personaje, lo dibuja en una hoja y escribe su nombre (con ayuda del docente). Luego, pegan los dibujos en un mural y cada alumno explica por qué eligió a ese personaje.", "materiales": ["Cuento", "Hojas", "Colores", "Pegamento", "Cartulina para mural"], "grado": "1°" },
    { "area": "Comprensión lectora", "nivel": 1, "nombre": "El dado de las preguntas", "duracion": 10, "descripcion": "El docente prepara un dado con preguntas (¿Quién?, ¿Dónde?, ¿Qué?, ¿Cuándo?, ¿Por qué?). Después de leer un cuento, los alumnos tiran el dado y responden la pregunta que sale (con apoyo del docente).", "materiales": ["Dado con preguntas", "Cuento"], "grado": "1°" },
    { "area": "Comprensión lectora", "nivel": 1, "nombre": "El teatro de sombras del cuento", "duracion": 15, "descripcion": "El docente lee un cuento corto. Los alumnos, con ayuda del docente, dibujan personajes en cartulina y los recortan. Luego, con una linterna y una tela blanca, representan el cuento con sombras chinescas. El docente apoya a quienes tienen dificultad.", "materiales": ["Cuento", "Cartulina", "Tijeras", "Palitos de madera", "Linterna", "Tela blanca"], "grado": "1°" },
    { "area": "Comprensión lectora", "nivel": 1, "nombre": "El collage del cuento", "duracion": 15, "descripcion": "El docente lee un cuento. Los alumnos recortan imágenes de revistas que representen lo que pasó en el cuento. Las pegan en una hoja en el orden correcto (con apoyo del docente). Luego, cuentan el cuento usando el collage.", "materiales": ["Cuento", "Revistas", "Tijeras", "Pegamento", "Hojas"], "grado": "1°" },
    { "area": "Comprensión lectora", "nivel": 1, "nombre": "El cuento de las preguntas con colores", "duracion": 10, "descripcion": "El docente lee un cuento y asigna colores a preguntas (rojo = quién, azul = dónde, verde = qué). Después, los alumnos responden las preguntas usando el color correspondiente. El docente apoya a quienes tienen dificultad.", "materiales": ["Cuento", "Tarjetas de colores", "Lista de preguntas"], "grado": "1°" },

    // ------------------------------------------------------------
    // COMPRENSIÓN LECTORA — NIVEL 2
    // ------------------------------------------------------------
    { "area": "Comprensión lectora", "nivel": 2, "nombre": "Preguntas de colores", "duracion": 15, "descripcion": "Después de leer, se formulan preguntas: Rojo (¿Quién?), Azul (¿Dónde?), Verde (¿Cuándo?), Naranja (¿Por qué?).", "materiales": ["Texto", "Tarjetas de colores", "Marcadores"], "grado": "2°" },
    { "area": "Comprensión lectora", "nivel": 2, "nombre": "El titular", "duracion": 10, "descripcion": "Después de leer un texto breve, el alumno inventa 3 posibles titulares y elige el que mejor resuma la idea principal.", "materiales": ["Texto breve", "Pizarra o papel"], "grado": "2°" },
    { "area": "Comprensión lectora", "nivel": 2, "nombre": "El resumen con 5 dedos", "duracion": 10, "descripcion": "Técnica del resumen con los 5 dedos: Pulgar (Personajes), Índice (Lugar), Corazón (Problema), Anular (Solución), Meñique (Final).", "materiales": ["Texto leído", "Hoja de trabajo"], "grado": "2°" },
    { "area": "Comprensión lectora", "nivel": 2, "nombre": "¿De qué se trata este libro?", "duracion": 15, "descripcion": "Los alumnos predicen el contenido de un libro a partir del título y las ilustraciones, y verifican su predicción al leer.", "materiales": ["Libros variados"], "grado": "2°" },
    { "area": "Comprensión lectora", "nivel": 2, "nombre": "Adivina de quién se trata (2°)", "duracion": 15, "descripcion": "Los alumnos describen oralmente a personas para que otros adivinen de quién se trata, desarrollando la expresión oral y la comprensión.", "materiales": ["Ninguno"], "grado": "2°" },
    { "area": "Comprensión lectora", "nivel": 2, "nombre": "Cuenta cuentos (2°)", "duracion": 15, "descripcion": "Los niños desarrollan la expresión oral contando cuentos, trabajando la secuencia y la claridad.", "materiales": ["Ninguno"], "grado": "2°" },
    { "area": "Comprensión lectora", "nivel": 2, "nombre": "Ponle título al texto", "duracion": 15, "descripcion": "Los alumnos leen un texto sin título y proponen títulos que identifiquen su contenido. Se discute la pertinencia de cada propuesta.", "materiales": ["Texto sin título"], "grado": "2°" },
    { "area": "Comprensión lectora", "nivel": 2, "nombre": "Versiones diferentes", "duracion": 15, "descripcion": "Los alumnos observan los cambios de significado que se producen en un cuento cuando se modifica alguna de sus partes.", "materiales": ["Cuento clásico"], "grado": "2°" },
    { "area": "Comprensión lectora", "nivel": 2, "nombre": "Escritores de cuentos", "duracion": 15, "descripcion": "Los alumnos redactan cuentos, identificando la estructura de introducción, nudo y desenlace.", "materiales": ["Hojas", "Lápices", "Colores"], "grado": "2°" },

    // ------------------------------------------------------------
    // COMPRENSIÓN LECTORA — NIVEL 3
    // ------------------------------------------------------------
    { "area": "Comprensión lectora", "nivel": 3, "nombre": "Inferencias en cadena", "duracion": 15, "descripcion": "Se lee un microcuento donde no todo está explícito. El alumno responde: ¿Qué pasó antes? ¿Qué pasará después? justificando con pistas.", "materiales": ["Microcuento o noticia", "Hoja de inferencias"], "grado": "3°" },
    { "area": "Comprensión lectora", "nivel": 3, "nombre": "El debate (comprensión)", "duracion": 15, "descripcion": "Se lee un texto con un tema polémico. El grupo se divide para argumentar a favor y en contra, usando la información del texto.", "materiales": ["Texto polémico"], "grado": "3°" },
    { "area": "Comprensión lectora", "nivel": 3, "nombre": "La historia desde otro punto de vista", "duracion": 15, "descripcion": "Después de leer un cuento, el alumno reescribe una escena desde la perspectiva de otro personaje (ej. el lobo en Caperucita Roja).", "materiales": ["Cuento", "Cuaderno"], "grado": "3°" },
    { "area": "Comprensión lectora", "nivel": 3, "nombre": "Adivina de quién se trata (3°)", "duracion": 15, "descripcion": "Los alumnos describen personas tomando en cuenta sus características físicas y de personalidad, para que otros adivinen de quién se trata.", "materiales": ["Ninguno"], "grado": "3°" },
    { "area": "Comprensión lectora", "nivel": 3, "nombre": "Mi propia historia", "duracion": 15, "descripcion": "Los alumnos relatan oralmente su historia personal y comparten con sus compañeros los hechos más significativos.", "materiales": ["Ninguno"], "grado": "3°" },
    { "area": "Comprensión lectora", "nivel": 3, "nombre": "Las biografías", "duracion": 15, "descripcion": "Los alumnos siguen el orden cronológico de los hechos al escribir un texto narrativo biográfico.", "materiales": ["Texto biográfico", "Hojas", "Lápices"], "grado": "3°" },
    { "area": "Comprensión lectora", "nivel": 3, "nombre": "¿Qué dice el periódico?", "duracion": 15, "descripcion": "Los niños conocen la forma como se organiza la información en las notas periodísticas y el uso de recursos fotográficos y tipográficos.", "materiales": ["Periódicos", "Tijeras", "Pegamento"], "grado": "3°" },
    { "area": "Comprensión lectora", "nivel": 3, "nombre": "El tema del que les voy a hablar", "duracion": 15, "descripcion": "Los niños organizan sus ideas para exponer un tema ante el grupo, utilizando apoyos gráficos.", "materiales": ["Hojas", "Marcadores", "Cartulinas"], "grado": "3°" },
    { "area": "Comprensión lectora", "nivel": 3, "nombre": "Leer y compartir", "duracion": 15, "descripcion": "Los alumnos comparten sus ideas y opiniones respecto de un texto leído en grupo, fomentando la discusión y el intercambio.", "materiales": ["Texto", "Libro de lecturas"], "grado": "3°" },
    { "area": "Comprensión lectora", "nivel": 3, "nombre": "Para elaborar un resumen (3°)", "duracion": 15, "descripcion": "Los alumnos identifican las ideas principales de un texto y elaboran un resumen escrito.", "materiales": ["Texto descriptivo", "Hojas", "Lápices"], "grado": "3°" },
    { "area": "Comprensión lectora", "nivel": 3, "nombre": "El mapa conceptual", "duracion": 15, "descripcion": "El alumno elabora un mapa conceptual de un texto informativo, identificando el tema principal y las ideas secundarias.", "materiales": ["Texto informativo", "Hoja y colores"], "grado": "4°" },
    { "area": "Comprensión lectora", "nivel": 3, "nombre": "Compara y contrasta", "duracion": 15, "descripcion": "Se leen dos textos sobre un mismo tema. El alumno llena un diagrama de Venn para comparar la información presentada.", "materiales": ["Dos textos sobre el mismo tema", "Hoja de trabajo"], "grado": "4°" },
    { "area": "Comprensión lectora", "nivel": 3, "nombre": "De qué platicamos hoy", "duracion": 15, "descripcion": "Los alumnos leen un texto y conversan para intercambiar opiniones a partir de la lectura. Se trabaja la comprensión y la argumentación.", "materiales": ["Texto", "Guía de preguntas"], "grado": "4°" },
    { "area": "Comprensión lectora", "nivel": 3, "nombre": "Leamos un cuento (4°)", "duracion": 15, "descripcion": "Los alumnos identifican el personaje principal de un cuento, la introducción, el nudo y el desenlace de la historia.", "materiales": ["Cuento", "Hojas para esquema"], "grado": "4°" },
    { "area": "Comprensión lectora", "nivel": 3, "nombre": "¿Por qué? (4°)", "duracion": 15, "descripcion": "Los alumnos reconocen la relación causa-consecuencia en los elementos de un texto narrativo (historia, novela, cuento, leyenda, noticia).", "materiales": ["Texto narrativo", "Cuaderno"], "grado": "4°" },
    { "area": "Comprensión lectora", "nivel": 3, "nombre": "Cómo se escriben los cuentos (4°)", "duracion": 15, "descripcion": "Los alumnos utilizan un organizador gráfico para planear y escribir un cuento, identificando título, personajes, lugar, época, inicio, nudo y desenlace.", "materiales": ["Hojas", "Plumones", "Cinta para pegar"], "grado": "4°" },
    { "area": "Comprensión lectora", "nivel": 3, "nombre": "Imagina de qué se trata (5°)", "duracion": 15, "descripcion": "Los alumnos realizan un muestreo y elaboran predicciones sobre el contenido de un texto antes de leerlo. Confrontan predicciones con la lectura.", "materiales": ["Texto (noticia, cuento, artículo informativo)"], "grado": "5°" },
    { "area": "Comprensión lectora", "nivel": 3, "nombre": "Antes de leer (5°)", "duracion": 15, "descripcion": "Los alumnos activan sus conocimientos previos sobre el tema que leerán, mediante lluvia de palabras, preguntas al texto o conversación previa.", "materiales": ["Texto", "Pizarrón"], "grado": "5°" },
    { "area": "Comprensión lectora", "nivel": 3, "nombre": "Rearmar textos", "duracion": 15, "descripcion": "Los alumnos rearman textos desordenados, trabajando la comprensión del orden de sucesos y la coherencia textual.", "materiales": ["Texto desordenado en tiras o párrafos"], "grado": "5°" },
    { "area": "Comprensión lectora", "nivel": 3, "nombre": "Puntos de vista", "duracion": 15, "descripcion": "Los alumnos discuten sobre un tema, manteniéndose en el tema, respetando turnos y argumentando sus puntos de vista.", "materiales": ["Ninguno"], "grado": "5°" },
    { "area": "Comprensión lectora", "nivel": 3, "nombre": "Los artículos de opinión", "duracion": 15, "descripcion": "Los alumnos identifican la función y características de los artículos de opinión, distinguiendo entre hechos y opiniones.", "materiales": ["Artículos de opinión", "Periódicos"], "grado": "5°" },
    { "area": "Comprensión lectora", "nivel": 3, "nombre": "Reseñas de cine", "duracion": 15, "descripcion": "Los alumnos escriben reseñas de cine utilizando organizadores gráficos para planear su texto.", "materiales": ["Hojas", "Lápices", "Películas o sinopsis"], "grado": "5°" },
    { "area": "Comprensión lectora", "nivel": 3, "nombre": "Antes de leer (6°)", "duracion": 15, "descripcion": "Los alumnos amplían su comprensión lectora activando conocimientos previos, estableciendo propósitos de lectura y elaborando predicciones.", "materiales": ["Texto", "Pizarrón"], "grado": "6°" },
    { "area": "Comprensión lectora", "nivel": 3, "nombre": "El capítulo de hoy (6°)", "duracion": 15, "descripcion": "Los alumnos conocen y aprecian la novela a través de la lectura en episodios. Se trabajan ideas principales y el género literario.", "materiales": ["Novela infantil o juvenil"], "grado": "6°" },
    { "area": "Comprensión lectora", "nivel": 3, "nombre": "Hechos y opiniones", "duracion": 15, "descripcion": "Los alumnos distinguen entre hechos y opiniones en un texto, desarrollando habilidades de pensamiento crítico.", "materiales": ["Artículos de opinión", "Noticias"], "grado": "6°" },
    { "area": "Comprensión lectora", "nivel": 3, "nombre": "Las partes del cuento (6°)", "duracion": 15, "descripcion": "Los alumnos identifican la estructura de los cuentos (planteamiento, nudo, desenlace) y sus elementos (personajes, lugar, tiempo).", "materiales": ["Cuentos variados", "Hojas para esquema"], "grado": "6°" },

    // ============================================================
    // SECUNDARIA
    // ============================================================

    // ------------------------------------------------------------
    // SECUNDARIA — FICHEROS ADAPTADOS (Categoría 1)
    // ------------------------------------------------------------

    // Comprensión lectora (Nivel 3)
    { "area": "Comprensión lectora", "nivel": 3, "nombre": "El debate (secundaria)", "duracion": 15, "descripcion": "Se lee un texto con un tema polémico de interés adolescente (ej. '¿Es beneficioso el uso de redes sociales?', '¿Deben los adolescentes tener horario para usar el celular?'). El grupo se divide en dos equipos para argumentar a favor y en contra, usando la información del texto como base. El docente modera y promueve el respeto de turnos.", "materiales": ["Texto polémico (artículo de opinión, noticia)", "Pizarrón para anotar argumentos"], "grado": "3° sec" },
    { "area": "Comprensión lectora", "nivel": 3, "nombre": "Los artículos de opinión (secundaria)", "duracion": 15, "descripcion": "Los alumnos leen un artículo de opinión de un periódico nacional. Identifican la tesis, los argumentos y la conclusión. Luego, escriben su propia opinión sobre el mismo tema, utilizando la estructura del artículo. Se comparten en parejas o en grupo.", "materiales": ["Artículos de opinión (editoriales)", "Hojas", "Lápices"], "grado": "3° sec" },
    { "area": "Comprensión lectora", "nivel": 3, "nombre": "Hechos y opiniones (secundaria)", "duracion": 15, "descripcion": "Se presenta a los alumnos una noticia y un artículo de opinión sobre el mismo tema. Los alumnos deben distinguir en cada texto qué es un hecho (información verificable) y qué es una opinión (punto de vista del autor). Se discute en grupo la importancia de esta distinción.", "materiales": ["Noticia", "Artículo de opinión sobre el mismo tema", "Hoja de trabajo"], "grado": "2° sec" },
    { "area": "Comprensión lectora", "nivel": 3, "nombre": "Reseñas de cine o series (secundaria)", "duracion": 15, "descripcion": "Los alumnos escriben una reseña de una película o serie que hayan visto recientemente. Utilizan un organizador gráfico para planear su texto: sinopsis, opinión, recomendación. Luego comparten su reseña con el grupo y discuten sobre los gustos y preferencias.", "materiales": ["Hojas", "Lápices", "Organizador gráfico (opcional)"], "grado": "2° sec" },
    { "area": "Comprensión lectora", "nivel": 3, "nombre": "El capítulo de hoy (secundaria)", "duracion": 15, "descripcion": "Lectura en voz alta de una novela juvenil (ej. 'El principito', 'Crónicas de una muerte anunciada', 'El túnel') por episodios. Cada sesión se lee un capítulo y se comentan las ideas principales, los personajes y las predicciones. El docente modela la lectura expresiva.", "materiales": ["Novela juvenil", "Marcadores de página"], "grado": "3° sec" },

    // Escritura (Nivel 3)
    { "area": "Escritura", "nivel": 3, "nombre": "Escribo mi opinión (secundaria)", "duracion": 15, "descripcion": "Los alumnos eligen un tema de interés escolar o comunitario (ej. 'La basura en la escuela', 'El uso del celular en clase'). Escriben una carta al director o un artículo de opinión, expresando su punto de vista y proponiendo soluciones. Se revisan en parejas y se corrigen.", "materiales": ["Hojas", "Lápices", "Ejemplos de cartas al director"], "grado": "3° sec" },
    { "area": "Escritura", "nivel": 3, "nombre": "La noticia (secundaria)", "duracion": 15, "descripcion": "Los alumnos escriben una noticia sobre un evento escolar (ej. 'Feria de ciencias', 'Partido de futbol', 'Visita del director'). Utilizan el formato de noticia: titular, entradilla, cuerpo y cierre. Se publican en un periódico mural o digital.", "materiales": ["Periódicos (para analizar formato)", "Hojas", "Lápices", "Computadora (opcional)"], "grado": "2° sec" },
    { "area": "Escritura", "nivel": 3, "nombre": "Álbum de recuerdos (secundaria)", "duracion": 15, "descripcion": "Los alumnos crean un álbum o diario de su transición a secundaria, o de experiencias significativas de su vida. Escriben relatos breves, incluyen fotos o dibujos, y comparten algunas páginas con el grupo. Es una actividad para expresar emociones y reflexionar sobre la identidad.", "materiales": ["Fotos", "Hojas", "Colores", "Carpeta o libreta"], "grado": "1° sec" },

    // Expresión oral (Nivel 3)
    { "area": "Expresión oral", "nivel": 3, "nombre": "El noticiero (secundaria)", "duracion": 15, "descripcion": "Los alumnos preparan y presentan un noticiero escolar o un podcast. Se organizan en equipos para cubrir diferentes secciones (noticias locales, deportes, cultura, entrevistas). Practican la dicción, entonación y fluidez al narrar.", "materiales": ["Periódicos", "Micrófono de juguete", "Grabadora (opcional)"], "grado": "2° sec" },
    { "area": "Expresión oral", "nivel": 3, "nombre": "La asamblea del grupo (secundaria)", "duracion": 15, "descripcion": "Se realiza una asamblea para discutir problemas o proyectos del grupo. Los alumnos expresan sus opiniones, críticas y propuestas con respeto, practicando el manejo de turnos y la claridad al hablar. Se toman acuerdos por consenso.", "materiales": ["Ninguno", "Pizarrón para anotar acuerdos"], "grado": "1° sec" },
    { "area": "Expresión oral", "nivel": 3, "nombre": "Quiero preguntarte (secundaria)", "duracion": 15, "descripcion": "Se realizan entrevistas colectivas a un compañero sobre temas de interés adolescente (ej. 'Mi pasatiempo favorito', 'Lo que pienso del futuro'). El entrevistado elige un tema y el grupo formula preguntas. Se trabaja la escucha activa y la iniciativa al hablar.", "materiales": ["Ninguno"], "grado": "1° sec" },
    { "area": "Expresión oral", "nivel": 3, "nombre": "Improvisaciones (secundaria)", "duracion": 15, "descripcion": "Los alumnos improvisan diálogos a partir de situaciones dadas (ej. 'Discutir con un amigo', 'Pedir un aumento', 'Entrevista de trabajo'). Se trabaja la expresividad del cuerpo y la voz, y la fluidez en el diálogo.", "materiales": ["Tarjetas con situaciones"], "grado": "3° sec" },

    // Reflexión sobre la lengua (Nivel 3)
    { "area": "Reflexión sobre la lengua", "nivel": 3, "nombre": "Sentido figurado (secundaria)", "duracion": 15, "descripcion": "Los alumnos analizan el lenguaje figurado en canciones, poemas y refranes. Identifican metáforas, símiles y personificaciones, y discuten su significado. Luego, crean sus propias metáforas para describir emociones o situaciones.", "materiales": ["Canciones", "Poemas", "Refranes", "Hojas", "Lápices"], "grado": "3° sec" },
    { "area": "Reflexión sobre la lengua", "nivel": 3, "nombre": "Inventa palabras (secundaria)", "duracion": 15, "descripcion": "Los alumnos crean palabras nuevas utilizando prefijos y sufijos (ej. 'ecofobia', 'ciberadicción') para nombrar conceptos actuales. Explican el significado de su palabra inventada y la usan en una oración. Se comparten en grupo.", "materiales": ["Pizarrón", "Diccionario", "Hojas", "Lápices"], "grado": "2° sec" },
    { "area": "Reflexión sobre la lengua", "nivel": 3, "nombre": "Para ampliar el vocabulario (secundaria)", "duracion": 15, "descripcion": "Los alumnos utilizan estrategias para ampliar su vocabulario: deducir significado por contexto, usar sinónimos y antónimos, crear redes de palabras, y consultar el diccionario. Se trabaja con textos académicos de otras asignaturas.", "materiales": ["Textos académicos (Ciencias, Historia)", "Diccionario", "Cuaderno"], "grado": "1° sec" },

    // ------------------------------------------------------------
    // SECUNDARIA — REZAGO (Categoría 2)
    // Todas las actividades de esta categoría son de nivel 1
    // y están pensadas para 1° de secundaria, como refuerzo.
    // ------------------------------------------------------------

    // Fluidez (Nivel 1)
    { "area": "Fluidez", "nivel": 1, "nombre": "La frase de hoy: repetición guiada (secundaria)", "duracion": 5, "descripcion": "El docente escribe una frase de interés adolescente (ej. 'El esfuerzo vale la pena') en el pizarrón. La lee en voz alta 3 veces mientras los alumnos la siguen con el dedo. Luego los alumnos la repiten al unísono 3 veces. Después, 3 alumnos voluntarios la leen individualmente. La frase se mantiene visible durante toda la sesión.", "materiales": ["Pizarrón", "Marcador"], "grado": "1° sec" },
    { "area": "Fluidez", "nivel": 1, "nombre": "El tren de las palabras conocidas (secundaria)", "duracion": 5, "descripcion": "El docente prepara tarjetas con palabras de materias (ej. 'ecosistema', 'fotosíntesis', 'revolución'). Cada alumno toma una tarjeta, la lee en voz alta y la coloca en el 'tren' (hilera). El siguiente alumno lee su palabra y la coloca junto a la anterior. Al final, leen todo el tren de palabras en orden.", "materiales": ["Tarjetas con palabras (al menos 2 por alumno)"], "grado": "1° sec" },

    // Precisión (Nivel 1)
    { "area": "Precisión", "nivel": 1, "nombre": "El detective de letras (secundaria)", "duracion": 5, "descripcion": "El docente escribe una palabra de materia (ej. 'excepción') en el pizarrón y pide a los alumnos que busquen una letra específica (ej. '¿Dónde está la 'c'?'). El alumno pasa al pizarrón y señala la letra. Luego, entre todos, cuentan cuántas veces aparece esa letra. Se repite con 3-4 palabras.", "materiales": ["Pizarrón", "Marcador"], "grado": "1° sec" },
    { "area": "Precisión", "nivel": 1, "nombre": "El semáforo de la escritura (secundaria)", "duracion": 10, "descripcion": "El docente dice una palabra de una materia y los alumnos la escriben en sus pizarras individuales. Si está bien, se pone un círculo verde. Si tiene errores, se pone un círculo amarillo y el docente apoya al alumno a corregir. Se repite con 5-6 palabras.", "materiales": ["Pizarras individuales", "Marcadores", "Tarjetas verdes y amarillas"], "grado": "1° sec" },

    // Atención a palabras complejas (Nivel 1)
    { "area": "Atención a palabras complejas", "nivel": 1, "nombre": "El cazador de la letra misteriosa (secundaria)", "duracion": 5, "descripcion": "El docente elige una letra compleja (ej. 'h', 'g' con sonido /x/). Muestra una tarjeta y pide a los alumnos que busquen en un texto de una materia palabras que contengan esa letra. Cada alumno encuentra una palabra, la escribe en su cuaderno y la comparte con el grupo.", "materiales": ["Tarjetas con letras complejas", "Textos de materias (Ciencias, Historia)"], "grado": "1° sec" },
    { "area": "Atención a palabras complejas", "nivel": 1, "nombre": "La sopa de letras fácil (secundaria)", "duracion": 10, "descripcion": "El docente prepara una sopa de letras con vocabulario de una materia (ej. 'célula', 'núcleo', 'membrana'). Los alumnos buscan las palabras y las encierran. Luego, las escriben en su cuaderno y definen su significado.", "materiales": ["Sopa de letras temática", "Lápices de colores", "Diccionario"], "grado": "1° sec" },

    // Uso de la voz (Nivel 1)
    { "area": "Uso de la voz", "nivel": 1, "nombre": "La máquina de las voces divertidas (secundaria)", "duracion": 5, "descripcion": "El docente prepara tarjetas con personajes (robot, abuelita, locutor de radio, científico). Cada alumno toma una tarjeta y debe leer una frase de un texto dramático o poético imitando la voz del personaje. El grupo adivina qué personaje es.", "materiales": ["Tarjetas con personajes", "Textos dramáticos o poéticos cortos"], "grado": "1° sec" },
    { "area": "Uso de la voz", "nivel": 1, "nombre": "El micrófono de la confianza (secundaria)", "duracion": 5, "descripcion": "El docente usa un micrófono de juguete. Cada alumno pasa al frente, sostiene el micrófono y lee una frase de un texto (poema, noticia, fragmento de novela). El micrófono ayuda a dar confianza y a escucharse mejor. Se graba para autoevaluarse.", "materiales": ["Micrófono de juguete", "Textos variados", "Grabadora (opcional)"], "grado": "1° sec" },

    // Seguridad y disposición (Nivel 1)
    { "area": "Seguridad y disposición", "nivel": 1, "nombre": "La caja de los logros lectores (secundaria)", "duracion": 10, "descripcion": "El docente prepara una caja decorada con la palabra 'Logros'. Cada vez que un alumno lee un texto complejo o comprende un concepto nuevo, escribe su logro en una tarjeta y la deposita en la caja. Al final de la semana, se leen algunos logros y se celebran.", "materiales": ["Caja decorada", "Tarjetas", "Lápices de colores"], "grado": "1° sec" },

    // Comprensión lectora (Nivel 1)
    { "area": "Comprensión lectora", "nivel": 1, "nombre": "El dado de las preguntas (secundaria)", "duracion": 10, "descripcion": "El docente prepara un dado con preguntas (¿Quién?, ¿Dónde?, ¿Qué?, ¿Cuándo?, ¿Por qué?, ¿Cómo?). Después de leer un texto de una materia, los alumnos tiran el dado y responden la pregunta que sale (con apoyo del docente). Se trabaja la comprensión literal.", "materiales": ["Dado con preguntas", "Texto de materia"], "grado": "1° sec" },

    // ------------------------------------------------------------
    // SECUNDARIA — DINÁMICAS GRUPALES DE FOMENTO A LA LECTURA (Categoría 3)
    // ------------------------------------------------------------

    // Comprensión lectora (Nivel 3)
    { "area": "Comprensión lectora", "nivel": 3, "nombre": "Círculo de lectura (secundaria)", "duracion": 15, "descripcion": "Los alumnos se sientan en círculo. Cada uno tiene una copia del mismo texto breve (cuento, poema, artículo). Por turnos, leen un párrafo en voz alta. Después, el docente guía una conversación sobre el texto: ¿Qué les pareció? ¿Qué emociones les provocó? ¿Qué preguntas les surgieron? Se fomenta el respeto y la escucha activa.", "materiales": ["Texto breve (cuento, poema, artículo)", "Copias para todos"], "grado": "1° sec" },
    { "area": "Comprensión lectora", "nivel": 3, "nombre": "La hora del cuento (secundaria)", "duracion": 15, "descripcion": "El docente o un alumno voluntario lee en voz alta un cuento corto, un relato de terror, ciencia ficción o realismo mágico. Se ambienta el espacio con luz tenue o música. Después de la lectura, se abre un espacio para comentar libremente las impresiones.", "materiales": ["Cuento o relato corto"], "grado": "1° sec" },
    { "area": "Comprensión lectora", "nivel": 3, "nombre": "Cuento congelado (secundaria)", "duracion": 15, "descripcion": "Después de leer un cuento o fragmento de novela, los alumnos se organizan en equipos. Cada equipo elige una escena clave del texto y la representa como una 'escena congelada' (todos los integrantes adoptan una posición determinada y no se mueven). Los otros equipos deben adivinar qué escena es. Se fomenta la creatividad y la comprensión.", "materiales": ["Texto leído previamente"], "grado": "2° sec" },
    { "area": "Comprensión lectora", "nivel": 3, "nombre": "Cuento con sombras chinescas (secundaria)", "duracion": 15, "descripcion": "Los alumnos leen un cuento o poema. Luego, en equipos, crean siluetas de los personajes en cartulina y las recortan. Con una linterna y una tela blanca, representan el texto con sombras chinescas, mientras otro equipo narra la historia. Se trabaja la comprensión y la expresión oral.", "materiales": ["Cartulina", "Tijeras", "Palitos de madera", "Linterna", "Tela blanca", "Texto"], "grado": "3° sec" },
    { "area": "Comprensión lectora", "nivel": 3, "nombre": "Cuento con sonidos (secundaria)", "duracion": 15, "descripcion": "El docente lee un texto (cuento, poema, noticia) y los alumnos, organizados en equipos, deben acompañar la lectura con efectos de sonido (viento, pasos, lluvia, objetos) utilizando sus voces u objetos del aula. Se trabaja la atención y la creatividad.", "materiales": ["Texto", "Objetos para hacer sonidos (opcional)"], "grado": "2° sec" },
    { "area": "Comprensión lectora", "nivel": 3, "nombre": "Pregúntale al poema (secundaria)", "duracion": 15, "descripcion": "El docente selecciona varios poemas. Los alumnos, en equipos, formulan preguntas personales o existenciales (ej. '¿Qué es el amor?', '¿Qué es la soledad?'). Luego, buscan en los poemas versos que puedan 'responder' a sus preguntas. Se comparten las respuestas y se reflexiona sobre el poder de la poesía.", "materiales": ["Libros de poesía", "Hojas", "Lápices"], "grado": "3° sec" },
    { "area": "Comprensión lectora", "nivel": 3, "nombre": "Lectura cubista (secundaria)", "duracion": 15, "descripcion": "El docente lee un texto descriptivo (poema, fragmento de novela). Los alumnos se organizan en equipos y cada equipo concentra su atención en un aspecto: sonidos, olores, colores, sabores, sensaciones táctiles. Después, comparten lo que 'sintieron' al leer. Se trabaja la lectura sensorial y la imaginación.", "materiales": ["Texto descriptivo (poema, fragmento de novela)"], "grado": "3° sec" },

    // Expresión oral (Nivel 3)
    { "area": "Expresión oral", "nivel": 3, "nombre": "Tertulia (secundaria)", "duracion": 15, "descripcion": "Se elige un tema de interés adolescente (ej. 'La amistad', 'Las redes sociales', 'La identidad'). El docente selecciona lecturas cortas (poemas, fragmentos de novelas, artículos) relacionadas con el tema. Los alumnos leen las lecturas y luego participan en una charla informal, compartiendo sus ideas y experiencias.", "materiales": ["Lecturas cortas sobre el tema elegido"], "grado": "3° sec" },

    // Uso de la voz (Nivel 3)
    { "area": "Uso de la voz", "nivel": 3, "nombre": "Teatro en atril (secundaria)", "duracion": 15, "descripcion": "Los alumnos leen un guión de teatro corto o un diálogo literario. Cada alumno asume un personaje y lee su parte en voz alta, cuidando la entonación y la expresividad. Se puede incluir un narrador y efectos de sonido. Se trabaja la fluidez y la interpretación.", "materiales": ["Guión de teatro corto o diálogo literario", "Copias para todos"], "grado": "2° sec" },

    // Atención a palabras complejas (Nivel 3)
    { "area": "Atención a palabras complejas", "nivel": 3, "nombre": "Busca a tu pareja (secundaria)", "duracion": 10, "descripcion": "El docente prepara tarjetas con la primera parte de un verso, refrán o frase célebre en unas, y la segunda parte en otras. Los alumnos deben caminar por el salón y encontrar a su 'pareja' (quien tenga la segunda parte). Cuando la encuentran, leen la frase completa y comentan su significado.", "materiales": ["Tarjetas con versos, refranes o frases célebres divididos en dos partes"], "grado": "1° sec" },

    // Escritura (Nivel 3)
    { "area": "Escritura", "nivel": 3, "nombre": "Dibujando mi propio final (secundaria)", "duracion": 15, "descripcion": "Los alumnos leen un cuento corto o un fragmento de novela. Luego, en equipos, dibujan un final diferente al original y lo explican al grupo. Después, escriben el nuevo final en prosa. Se trabaja la creatividad, la comprensión y la escritura.", "materiales": ["Texto (cuento o fragmento)", "Hojas", "Colores", "Lápices"], "grado": "2° sec" }

];
