// ============================================================
// SAAL - BANCO DE ACTIVIDADES DE INTERVENCIÓN
// Versión 1.0 - Julio 2025
// Basado en manuales y ficheros de actividades
// ============================================================

const bancoActividades = [
    // ============================================================
    // FLUIDEZ
    // ============================================================
    { "area": "Fluidez", "nivel": 1, "nombre": "Lectura en eco", "duracion": 5, "descripcion": "El docente lee una frase corta con buena entonación y el alumno la repite inmediatamente, imitando el ritmo, la velocidad y la entonación.", "materiales": ["Texto guía del docente con frases cortas"] },
    { "area": "Fluidez", "nivel": 1, "nombre": "Lectura con el dedo", "duracion": 5, "descripcion": "El alumno desliza su dedo índice debajo de las palabras mientras lee en voz baja o susurrada. Ayuda a mantener el ritmo visual y evitar saltos de línea.", "materiales": ["Texto individual (con letra grande)", "Dedo o señalador"] },
    { "area": "Fluidez", "nivel": 1, "nombre": "El eco de volumen", "duracion": 5, "descripcion": "El docente lee una palabra o frase en voz baja (susurro) y el alumno la repite en voz baja. Luego el docente la dice en voz alta y el alumno la repite en voz alta. Control de intensidad.", "materiales": ["Lista de palabras/frases cortas"] },
    { "area": "Fluidez", "nivel": 1, "nombre": "Ronda de rimas", "duracion": 10, "descripcion": "El docente escribe y lee una rima corta. Los alumnos la repiten varias veces, aumentando gradualmente la velocidad. Se puede hacer un juego de '¿quién la dice más rápido?'.", "materiales": ["Rima corta en el pizarrón o en una tarjeta"] },
    { "area": "Fluidez", "nivel": 1, "nombre": "Lectura por minuto (Nivel 1)", "duracion": 10, "descripcion": "El alumno lee un texto muy corto durante 1 minuto. El docente cuenta cuántas palabras leyó y lo registra. El objetivo es que el alumno vea su progreso cuando repita el texto.", "materiales": ["Texto corto (50-80 palabras)", "Cronómetro"] },
    { "area": "Fluidez", "nivel": 2, "nombre": "Lectura en eco grupal", "duracion": 10, "descripcion": "El docente lee una estrofa o un párrafo y todo el grupo lo repite al unísono. Luego, se divide al grupo en dos mitades que leen alternando párrafos para practicar la continuidad.", "materiales": ["Poema o canción escrita", "Pizarra"] },
    { "area": "Fluidez", "nivel": 2, "nombre": "Lectura por minuto (Nivel 2)", "duracion": 15, "descripcion": "El alumno lee un texto durante 1 minuto. Cuenta las palabras leídas correctamente y anota su marca. Vuelve a leer el mismo texto para intentar superar su propia marca.", "materiales": ["Texto corto (100-150 palabras)", "Cronómetro", "Registro de marcas"] },
    { "area": "Fluidez", "nivel": 2, "nombre": "La noticia en voz alta", "duracion": 15, "descripcion": "Los alumnos practican la lectura en voz alta de una noticia corta, cuidando la pronunciación y el ritmo. Luego la leen para un compañero.", "materiales": ["Noticia corta impresa (1 por alumno)"] },
    { "area": "Fluidez", "nivel": 2, "nombre": "Carrera de trabalenguas (fluidez)", "duracion": 10, "descripcion": "Se practica un trabalenguas en voz baja, luego en voz media y finalmente en voz alta, cuidando la dicción sin perder la velocidad. Es un ejercicio de fluidez.", "materiales": ["Tarjetas con trabalenguas"] },
    { "area": "Fluidez", "nivel": 2, "nombre": "El noticiero", "duracion": 10, "descripcion": "Cada alumno prepara la lectura de un párrafo de una noticia como si fuera un locutor. Se enfatiza la claridad, la velocidad adecuada y la entonación.", "materiales": ["Noticias cortas", "Micrófono de juguete (opcional)"] },
    { "area": "Fluidez", "nivel": 3, "nombre": "Teatro de voces (fluidez)", "duracion": 15, "descripcion": "Se asigna un personaje a cada alumno. Leen un diálogo poniendo énfasis en la expresividad, velocidad y volumen según el personaje (ej. abuelo lento, niño rápido, villano dramático).", "materiales": ["Guión de diálogo corto", "Tarjetas de personajes"] },
    { "area": "Fluidez", "nivel": 3, "nombre": "Lectura expresiva con emociones", "duracion": 15, "descripcion": "El alumno recibe un mismo párrafo y debe leerlo expresando diferentes emociones (alegría, tristeza, enojo, miedo). Se enfoca en la modulación de la voz y el ritmo.", "materiales": ["Texto de un párrafo", "Tarjetas de emociones"] },
    { "area": "Fluidez", "nivel": 3, "nombre": "Poesía coral", "duracion": 15, "descripcion": "El grupo ensaya y presenta un poema de forma coral, asignando versos a diferentes voces para lograr un efecto rítmico y expresivo.", "materiales": ["Poema", "Marcadores para resaltar partes"] },
    { "area": "Fluidez", "nivel": 3, "nombre": "Grabación y autoevaluación", "duracion": 15, "descripcion": "El alumno se graba leyendo un texto. Luego escucha su grabación y se autoevalúa en aspectos de fluidez, entonación y ritmo, identificando áreas de mejora.", "materiales": ["Texto", "Grabadora (celular)"] },
    { "area": "Fluidez", "nivel": 3, "nombre": "El locutor deportivo", "duracion": 10, "descripcion": "El alumno lee una narración de un partido o una noticia deportiva con la emoción y velocidad de un locutor profesional.", "materiales": ["Narración o noticia deportiva"] },

    // ============================================================
    // PRECISIÓN
    // ============================================================
    { "area": "Precisión", "nivel": 1, "nombre": "Cazador de sílabas", "duracion": 5, "descripcion": "Se muestra una palabra y el alumno debe palmear las sílabas mientras la dice (ej. Ma-ri-po-sa). Luego busca en un listado palabras con igual número de sílabas.", "materiales": ["Tarjetas de palabras con dibujos", "Palmas"] },
    { "area": "Precisión", "nivel": 1, "nombre": "Separa y lee", "duracion": 5, "descripcion": "El docente escribe palabras compuestas sin separación (ej. sacacorchos, parabrisas, abrelatas) y el alumno debe dividirlas en dos palabras, explicar su significado y leerlas.", "materiales": ["Pizarra", "Marcador"] },
    { "area": "Precisión", "nivel": 1, "nombre": "¿Cuántas letras?", "duracion": 5, "descripcion": "El docente dice una palabra y los alumnos, usando letras móviles o escribiendo, intentan adivinar cuántas letras tiene. Luego se escribe y se cuentan las letras juntos.", "materiales": ["Letras móviles", "Pizarra"] },
    { "area": "Precisión", "nivel": 1, "nombre": "Relaciona imagen y palabra", "duracion": 10, "descripcion": "Se presentan varias tarjetas con imágenes (ej. sol, luna, flor, gato) y varias tarjetas con sus nombres escritos. El alumno debe unir cada imagen con su palabra correspondiente.", "materiales": ["Tarjetas de imágenes", "Tarjetas con palabras"] },
    { "area": "Precisión", "nivel": 1, "nombre": "El sobre de palabras", "duracion": 10, "descripcion": "El alumno elige 4 palabras que quiere aprender. El docente las escribe en tarjetas y el alumno las guarda en un sobre. Se usan para jugar a clasificarlas (largas/cortas, por letra inicial, etc.).", "materiales": ["Sobre tamaño carta", "Tarjetas de cartoncillo"] },
    { "area": "Precisión", "nivel": 2, "nombre": "El intruso (precisión)", "duracion": 10, "descripcion": "Se escribe una lista de 5 palabras donde 4 comparten una característica (ej. todas riman, empiezan con la misma sílaba) y una no. El alumno debe identificar y justificar por qué la palabra es la intrusa.", "materiales": ["Listados impresos (de palabras)", "Lápiz"] },
    { "area": "Precisión", "nivel": 2, "nombre": "Palabras trampa", "duracion": 10, "descripcion": "Se lee un listado de palabras que se diferencian por una letra (pares mínimos: 'pera' y 'perra'; 'casa' y 'caza'; 'carro' y 'caro'). El alumno debe escribir la palabra que escucha y usarla en una frase.", "materiales": ["Listado de pares mínimos", "Cuaderno o pizarra"] },
    { "area": "Precisión", "nivel": 2, "nombre": "Ruleta de fonemas (precisión)", "duracion": 10, "descripcion": "Se gira una ruleta con fonemas (/r/, /rr/, /c/, /z/, /ll/). El alumno debe decir 3 palabras que contengan ese fonema y luego leer una oración con énfasis en ese sonido.", "materiales": ["Ruleta con fonemas", "Lista de oraciones"] },
    { "area": "Precisión", "nivel": 2, "nombre": "Completa la palabra (letra final)", "duracion": 10, "descripcion": "Se presenta una imagen y su palabra escrita con la última letra faltante. El alumno debe decir la palabra en voz alta, escuchar el último sonido y escribir la letra que falta.", "materiales": ["Tarjetas con imágenes y palabras incompletas", "Lápiz"] },
    { "area": "Precisión", "nivel": 2, "nombre": "Rompecabezas de sílabas", "duracion": 10, "descripcion": "El alumno recibe tarjetas con palabras divididas en sílabas (desordenadas). Debe armarlas para formar la palabra correcta.", "materiales": ["Tarjetas con sílabas de varias palabras"] },
    { "area": "Precisión", "nivel": 3, "nombre": "Acentuación detectivesca", "duracion": 15, "descripcion": "Se entrega un texto sin tildes. El alumno debe colocar las tildes que faltan y luego leer el texto respetando la correcta acentuación.", "materiales": ["Texto sin tildes", "Bolígrafo rojo"] },
    { "area": "Precisión", "nivel": 3, "nombre": "¿Con b o con v? (precisión)", "duracion": 15, "descripcion": "El dictado se centra en palabras con b y v. Después de escribir, el alumno revisa y justifica la escritura de esas palabras usando las reglas ortográficas.", "materiales": ["Lista de palabras con b y v", "Cuaderno"] },
    { "area": "Precisión", "nivel": 3, "nombre": "La letra H", "duracion": 15, "descripcion": "Se trabajan las palabras con H. El alumno lee un texto y subraya todas las palabras con H. Luego reflexiona sobre el por qué no tiene sonido y se escriben con H.", "materiales": ["Texto con muchas H", "Marcadores"] },
    { "area": "Precisión", "nivel": 3, "nombre": "Las palabras se transforman", "duracion": 10, "descripcion": "Juego de 'Escalera de palabras'. Se escribe una palabra y el siguiente jugador debe decir otra que empiece con la última letra de la palabra anterior. Se escribe en el pizarrón.", "materiales": ["Pizarrón o papel"] },
    { "area": "Precisión", "nivel": 3, "nombre": "Crucigramas (precisión)", "duracion": 15, "descripcion": "El alumno resuelve un crucigrama con palabras que contienen sílabas con dificultades ortográficas (gue/gui, ce/ci, etc.)", "materiales": ["Crucigrama impreso", "Lápiz"] },

    // ============================================================
    // ATENCIÓN A PALABRAS COMPLEJAS
    // ============================================================
    { "area": "Atención a palabras complejas", "nivel": 1, "nombre": "Subraya la palabra", "duracion": 5, "descripcion": "Se entrega un texto con palabras destacadas en negrita (ej. 'había', 'excepción', 'árbol', 'pájaro'). El alumno solo debe leer esas palabras en voz alta antes de leer el texto completo.", "materiales": ["Texto con palabras clave en negrita"] },
    { "area": "Atención a palabras complejas", "nivel": 1, "nombre": "Memoria visual", "duracion": 5, "descripcion": "Se muestra una palabra compleja (ej. 'ferrocarril', 'paraguas') durante 3 segundos. Luego se oculta y el alumno debe deletrearla y escribirla de memoria.", "materiales": ["Tarjetas de palabras complejas", "Pizarra individual"] },
    { "area": "Atención a palabras complejas", "nivel": 1, "nombre": "Caza de letras", "duracion": 5, "descripcion": "El docente muestra una palabra compleja y pide a los alumnos que busquen en ella una letra específica (ej. '¿Cuántas 'r' hay en ferrocarril?').", "materiales": ["Tarjetas con palabras complejas"] },
    { "area": "Atención a palabras complejas", "nivel": 2, "nombre": "Palabras trampa (atención)", "duracion": 10, "descripcion": "Se lee un listado de palabras que se diferencian por una letra (pares mínimos: 'casa' y 'caza'; 'carro' y 'caro'). El alumno debe escribir la palabra que escucha y usarla en una frase.", "materiales": ["Listado de pares mínimos", "Cuaderno"] },
    { "area": "Atención a palabras complejas", "nivel": 2, "nombre": "Lectura con lupa", "duracion": 10, "descripcion": "Se entrega un texto con palabras complejas resaltadas en amarillo. El alumno lee en voz alta y, al llegar a esas palabras, hace una pausa y las descompone en sílabas.", "materiales": ["Texto resaltado", "Lupa de cartón (opcional)"] },
    { "area": "Atención a palabras complejas", "nivel": 2, "nombre": "El cuento de las palabras difíciles", "duracion": 10, "descripcion": "El docente lee un cuento que contiene palabras complejas. Antes de leer, las escribe en el pizarrón y las trabaja (las descompone en sílabas, las repite).", "materiales": ["Cuento con vocabulario complejo", "Pizarrón"] },
    { "area": "Atención a palabras complejas", "nivel": 2, "nombre": "¡Cambia una letra!", "duracion": 10, "descripcion": "El docente escribe una palabra y los alumnos deben cambiarla, modificando una sola letra, para formar una palabra nueva. Por ejemplo: MESA -> MISA -> LISA -> PISA.", "materiales": ["Pizarrón", "Marcador"] },
    { "area": "Atención a palabras complejas", "nivel": 3, "nombre": "Análisis morfológico exprés", "duracion": 15, "descripcion": "El alumno lee un párrafo y subraya los prefijos y sufijos de las palabras complejas (ej. 'inútil', 'felicidad', 'submarino'). Luego explica cómo cambia el significado de la raíz.", "materiales": ["Párrafo con palabras derivadas", "Marcador"] },
    { "area": "Atención a palabras complejas", "nivel": 3, "nombre": "Palabras compuestas", "duracion": 15, "descripcion": "El alumno identifica y escribe palabras compuestas (ej. abrelatas, sacapuntas, mediodía). Luego las usa en oraciones.", "materiales": ["Lista de palabras compuestas", "Cuaderno"] },
    { "area": "Atención a palabras complejas", "nivel": 3, "nombre": "Homófonas", "duracion": 15, "descripcion": "El alumno trabaja con palabras homófonas (ej. 'tubo' y 'tuvo', 'valla' y 'vaya'). Escribe oraciones con cada una para comprender su significado.", "materiales": ["Lista de palabras homófonas", "Diccionario"] },
    { "area": "Atención a palabras complejas", "nivel": 3, "nombre": "La sopa de letras ortográfica", "duracion": 10, "descripcion": "Sopa de letras con palabras que contienen dificultades ortográficas. El alumno debe encontrarlas y escribirlas correctamente.", "materiales": ["Sopa de letras impresa", "Lápiz"] },
    { "area": "Atención a palabras complejas", "nivel": 3, "nombre": "El diccionario del grupo", "duracion": 15, "descripcion": "Cada alumno busca en el diccionario una palabra que no conozca, la escribe y la define con sus propias palabras para compartir con el grupo.", "materiales": ["Diccionario", "Cuaderno"] },

    // ============================================================
    // USO DE LA VOZ
    // ============================================================
    { "area": "Uso de la voz", "nivel": 1, "nombre": "Respiración de globo", "duracion": 5, "descripcion": "Ejercicio de respiración: inflar un globo al inspirar (llenar el abdomen) y desinflarlo al espirar diciendo 'ssssss'. Luego leer una frase corta con el aire controlado.", "materiales": ["Ninguno (imaginería)", "Globo real (opcional)"] },
    { "area": "Uso de la voz", "nivel": 1, "nombre": "Eco de volumen", "duracion": 5, "descripcion": "El docente lee una palabra en voz baja y el alumno la repite en voz baja. Luego el docente la dice en voz alta y el alumno la repite en voz alta. Control de intensidad.", "materiales": ["Lista de palabras"] },
    { "area": "Uso de la voz", "nivel": 1, "nombre": "El teléfono descompuesto (voz)", "duracion": 5, "descripcion": "Los alumnos se sientan en fila. El primero susurra una palabra o frase corta al oído del siguiente, y así sucesivamente. Se trabaja la claridad al hablar.", "materiales": ["Ninguno"] },
    { "area": "Uso de la voz", "nivel": 1, "nombre": "El sonido de los animales", "duracion": 5, "descripcion": "El docente lee un texto y los alumnos hacen el sonido del animal que se menciona. Se usa la voz para imitar.", "materiales": ["Texto con animales", "Imaginación"] },
    { "area": "Uso de la voz", "nivel": 2, "nombre": "Modulación de emociones (voz)", "duracion": 10, "descripcion": "Se entrega una misma oración (ej. 'Hoy es mi cumpleaños') y el alumno debe leerla con tono de: alegría, tristeza, sorpresa y enojo.", "materiales": ["Tarjetas de emociones", "Frase modelo"] },
    { "area": "Uso de la voz", "nivel": 2, "nombre": "Carrera de trabalenguas", "duracion": 10, "descripcion": "Se practica un trabalenguas en voz baja, luego en voz media y finalmente en voz alta, cuidando la dicción sin perder la velocidad.", "materiales": ["Tarjetas de trabalenguas"] },
    { "area": "Uso de la voz", "nivel": 2, "nombre": "Yo, el locutor", "duracion": 10, "descripcion": "El alumno lee una noticia corta imitando la voz de un locutor de radio o televisión, cuidando el volumen y la claridad.", "materiales": ["Noticia corta", "Micrófono de juguete"] },
    { "area": "Uso de la voz", "nivel": 2, "nombre": "El viento y el trueno", "duracion": 10, "descripcion": "Se practica el volumen. Para un texto sobre una tormenta, el alumno usa voz suave (como el viento) y voz fuerte (como el trueno) en las partes que correspondan.", "materiales": ["Texto con elementos de volumen"] },
    { "area": "Uso de la voz", "nivel": 2, "nombre": "Lectura con ritmo musical", "duracion": 10, "descripcion": "Se pone una canción instrumental de fondo y el alumno debe leer un poema con el ritmo de la música. Puede marcar el ritmo con palmas o instrumentos.", "materiales": ["Instrumentos de percusión", "Texto rítmico"] },
    { "area": "Uso de la voz", "nivel": 3, "nombre": "Locución de noticias", "duracion": 15, "descripcion": "El alumno lee una noticia como si fuera un locutor de radio, cuidando el volumen, las pausas y la entonación. Se graba y se autoevalúa.", "materiales": ["Noticia corta", "Grabadora (celular)"] },
    { "area": "Uso de la voz", "nivel": 3, "nombre": "Teatro de voces (voz)", "duracion": 15, "descripcion": "Se asigna un personaje a cada alumno. Leen un diálogo poniendo énfasis en la expresividad, velocidad y volumen según el personaje.", "materiales": ["Guión de diálogo", "Tarjetas de personajes"] },
    { "area": "Uso de la voz", "nivel": 3, "nombre": "Poesía con efectos de sonido", "duracion": 15, "descripcion": "Se prepara una poesía coral donde se incluyen efectos de sonido con la voz (susurros, ecos, onomatopeyas) para darle mayor expresividad.", "materiales": ["Poema", "Instrumentos de percusión"] },
    { "area": "Uso de la voz", "nivel": 3, "nombre": "El debate", "duracion": 15, "descripcion": "Se organiza un debate sencillo sobre un tema de interés. Los alumnos deben expresar sus argumentos con claridad, volumen adecuado y un tono persuasivo.", "materiales": ["Tema de debate", "Tarjetas para argumentos"] },
    { "area": "Uso de la voz", "nivel": 3, "nombre": "La entrevista radiofónica", "duracion": 15, "descripcion": "Los alumnos preparan y representan una entrevista de radio, trabajando la entonación y la naturalidad en el diálogo.", "materiales": ["Guión de entrevista", "Grabadora"] },

    // ============================================================
    // SEGURIDAD Y DISPOSICIÓN
    // ============================================================
    { "area": "Seguridad y disposición", "nivel": 1, "nombre": "Ritual de inicio", "duracion": 5, "descripcion": "Antes de leer, el alumno se sienta recto, coloca el texto frente a sus ojos, respira profundo y dice en voz baja: 'Estoy listo para leer'. Activa su disposición.", "materiales": ["Ninguno"] },
    { "area": "Seguridad y disposición", "nivel": 1, "nombre": "El espejo positivo", "duracion": 5, "descripcion": "El alumno se mira en un espejo pequeño mientras se dice a sí mismo: 'Soy un buen lector' y lee una frase corta mirándose a los ojos.", "materiales": ["Espejo pequeño"] },
    { "area": "Seguridad y disposición", "nivel": 1, "nombre": "¿Qué puedo leer?", "duracion": 5, "descripcion": "Exploración libre de la biblioteca del aula. Cada alumno elige un libro que le llame la atención, solo por su portada o título.", "materiales": ["Libros de la biblioteca del aula"] },
    { "area": "Seguridad y disposición", "nivel": 1, "nombre": "Lectura en voz baja para mí", "duracion": 5, "descripcion": "Se pide a los alumnos que lean en voz baja o susurrada un texto corto. El objetivo es que se escuchen a sí mismos sin la presión de un público.", "materiales": ["Texto corto para cada alumno"] },
    { "area": "Seguridad y disposición", "nivel": 2, "nombre": "Mis logros lectores", "duracion": 10, "descripcion": "El alumno lee un texto fácil y registra en su 'diario de lector' cuántas palabras leyó bien y qué hizo bien (ej. 'No me salté comas', 'Leí con buena entonación').", "materiales": ["Diario de lector", "Texto corto"] },
    { "area": "Seguridad y disposición", "nivel": 2, "nombre": "Aplausos por párrafo", "duracion": 10, "descripcion": "Por cada párrafo que el alumno lee sin errores, el grupo o el docente da una palmada. Se refuerza el esfuerzo y la atención sostenida.", "materiales": ["Texto por párrafos", "Palmas"] },
    { "area": "Seguridad y disposición", "nivel": 2, "nombre": "El lector recomendado", "duracion": 10, "descripcion": "Un alumno que ha leído un libro lo recomienda a sus compañeros. Describe de qué trata, por qué le gustó y convence a otros para leerlo. Gana confianza.", "materiales": ["Libro leído previamente"] },
    { "area": "Seguridad y disposición", "nivel": 2, "nombre": "¿Cómo me siento?", "duracion": 10, "descripcion": "Antes y después de una lectura, el alumno dibuja o escribe cómo se siente (nervioso, contento, confiado). Se abren conversaciones sobre las emociones.", "materiales": ["Hojas con caritas o espacio para dibujo"] },
    { "area": "Seguridad y disposición", "nivel": 2, "nombre": "Tarjetas de retos", "duracion": 10, "descripcion": "Se tienen tarjetas con pequeños desafíos de lectura (ej. 'Lee esta frase con la voz de tu abuelo', 'Lee este trabalenguas lo más rápido que puedas'). Se eligen al azar.", "materiales": ["Tarjetas con retos de lectura"] },
    { "area": "Seguridad y disposición", "nivel": 3, "nombre": "Lectura en cámara lenta", "duracion": 15, "descripcion": "El alumno lee un texto desafiante extremadamente lento, enfocándose en cada palabra. El objetivo no es la velocidad, sino la autoconfianza al enfrentar un texto difícil.", "materiales": ["Texto de nivel superior", "Cronómetro (para medir calma)"] },
    { "area": "Seguridad y disposición", "nivel": 3, "nombre": "El club de los lectores", "duracion": 15, "descripcion": "Se reúne un grupo pequeño para comentar un libro que todos han leído. Cada alumno comparte su opinión sin ser evaluado.", "materiales": ["Libro leído en común"] },
    { "area": "Seguridad y disposición", "nivel": 3, "nombre": "Mi lectura favorita", "duracion": 15, "descripcion": "Cada alumno elige su texto favorito y lo lee al grupo, explicando por qué le gusta. Se celebra la diversidad de gustos.", "materiales": ["Texto elegido por el alumno"] },
    { "area": "Seguridad y disposición", "nivel": 3, "nombre": "El crítico literario", "duracion": 15, "descripcion": "El alumno escribe una breve reseña de un libro que ha leído, destacando lo que le gustó y lo que no. Comparte su reseña con el grupo.", "materiales": ["Libro leído", "Hoja para reseña"] },

    // ============================================================
    // COMPRENSIÓN LECTORA
    // ============================================================
    { "area": "Comprensión lectora", "nivel": 1, "nombre": "Dibuja lo que lees", "duracion": 15, "descripcion": "El alumno lee una oración simple (ej. 'El perro corre bajo la lluvia') y hace un dibujo de ella. Luego explica su dibujo a un compañero.", "materiales": ["Oraciones ilustrables", "Hojas en blanco", "Colores"] },
    { "area": "Comprensión lectora", "nivel": 1, "nombre": "Ordena la historia", "duracion": 10, "descripcion": "Se entregan 4 viñetas desordenadas de un cuento conocido. El alumno las ordena, las lee y cuenta la historia con sus palabras.", "materiales": ["Viñetas impresas", "Tijeras"] },
    { "area": "Comprensión lectora", "nivel": 1, "nombre": "¿Qué pasó primero?", "duracion": 10, "descripcion": "Se lee un cuento corto. Luego se muestran 3 dibujos de la historia y se pregunta cuál pasó primero, cuál después y cuál al final.", "materiales": ["Cuento corto", "Dibujos"] },
    { "area": "Comprensión lectora", "nivel": 1, "nombre": "Sigue las instrucciones", "duracion": 10, "descripcion": "El docente da instrucciones orales sencillas (ej. 'Toca tu cabeza, luego toca tu nariz'), los alumnos las siguen. Luego se lee una instrucción sencilla en voz alta para que la sigan.", "materiales": ["Tarjetas con instrucciones"] },
    { "area": "Comprensión lectora", "nivel": 1, "nombre": "El personaje favorito", "duracion": 10, "descripcion": "Después de una lectura, el alumno elige su personaje favorito y lo describe con sus palabras (cómo es, qué hace, por qué le gusta).", "materiales": ["Cuento leído"] },
    { "area": "Comprensión lectora", "nivel": 2, "nombre": "Preguntas de colores", "duracion": 15, "descripcion": "Después de leer un texto, se formulan preguntas: Rojo (¿Quién?), Azul (¿Dónde?), Verde (¿Cuándo?), Naranja (¿Por qué?). El alumno responde señalando la evidencia en el texto.", "materiales": ["Texto", "Tarjetas de colores", "Marcadores"] },
    { "area": "Comprensión lectora", "nivel": 2, "nombre": "El titular", "duracion": 10, "descripcion": "Después de leer un texto breve, el alumno debe inventar 3 posibles titulares y elegir el que mejor resuma la idea principal.", "materiales": ["Texto breve", "Pizarra o papel"] },
    { "area": "Comprensión lectora", "nivel": 2, "nombre": "¿Qué pasaría si...?", "duracion": 10, "descripcion": "Se plantean preguntas hipotéticas sobre un texto leído (ej. '¿Qué pasaría si el personaje principal no hubiera hecho eso?').", "materiales": ["Texto leído"] },
    { "area": "Comprensión lectora", "nivel": 2, "nombre": "El resumen con 5 dedos", "duracion": 10, "descripcion": "Se enseña la técnica del resumen con los 5 dedos: Pulgar (Personajes), Índice (Lugar), Corazón (Problema), Anular (Solución), Meñique (Final).", "materiales": ["Texto leído", "Hoja de trabajo"] },
    { "area": "Comprensión lectora", "nivel": 2, "nombre": "Escucha y dibuja", "duracion": 15, "descripcion": "El docente lee una descripción detallada de un paisaje o personaje sin mostrar la imagen. El alumno debe escuchar y dibujar lo que se describe.", "materiales": ["Texto descriptivo", "Hojas para dibujo", "Colores"] },
    { "area": "Comprensión lectora", "nivel": 3, "nombre": "Inferencias en cadena", "duracion": 15, "descripcion": "Se lee un microcuento o una noticia donde no todo está explícito. El alumno debe responder: ¿Qué pasó antes? ¿Qué pasará después? ¿Qué pensaba el personaje? y justificar con pistas del texto.", "materiales": ["Microcuento o noticia", "Hoja de inferencias"] },
    { "area": "Comprensión lectora", "nivel": 3, "nombre": "El debate (comprensión)", "duracion": 15, "descripcion": "Se lee un texto con un tema polémico. El grupo se divide para argumentar a favor y en contra, usando la información del texto como base.", "materiales": ["Texto polémico"] },
    { "area": "Comprensión lectora", "nivel": 3, "nombre": "Compara y contrasta", "duracion": 15, "descripcion": "Se leen dos textos sobre un mismo tema. El alumno llena un diagrama de Venn para comparar la información presentada en cada uno.", "materiales": ["Dos textos sobre el mismo tema", "Hoja de trabajo"] },
    { "area": "Comprensión lectora", "nivel": 3, "nombre": "La historia desde otro punto de vista", "duracion": 15, "descripcion": "Después de leer un cuento, el alumno debe reescribir una escena desde la perspectiva de otro personaje (ej. el lobo en Caperucita Roja).", "materiales": ["Cuento", "Cuaderno"] },
    { "area": "Comprensión lectora", "nivel": 3, "nombre": "El mapa conceptual", "duracion": 15, "descripcion": "El alumno elabora un mapa conceptual sencillo de un texto informativo, identificando el tema principal y las ideas secundarias.", "materiales": ["Texto informativo", "Hoja y colores"] }
];
