// ============================================================
// SAAL - BANCO DE ACTIVIDADES (VERSIÓN COMPLETA)
// Integra las actividades seleccionadas y clasificadas por área y nivel
// ============================================================

const bancoActividades = [
    // ============================================================
    // FLUIDEZ
    // ============================================================
    { "area": "Fluidez", "nivel": 1, "nombre": "Lectura en eco", "duracion": 5, "descripcion": "El docente lee una frase corta con buena entonación y el alumno la repite inmediatamente, imitando el ritmo, la velocidad y la entonación.", "materiales": ["Texto guía del docente con frases cortas"] },
    { "area": "Fluidez", "nivel": 1, "nombre": "Lectura con el dedo", "duracion": 5, "descripcion": "El alumno desliza su dedo índice debajo de las palabras mientras lee en voz baja o susurrada para mantener el ritmo visual.", "materiales": ["Texto individual con letra grande", "Dedo o señalador"] },
    { "area": "Fluidez", "nivel": 1, "nombre": "El eco de volumen", "duracion": 5, "descripcion": "El docente lee una palabra en voz baja y el alumno la repite; luego en voz alta y el alumno repite. Control de intensidad.", "materiales": ["Lista de palabras/frases cortas"] },
    { "area": "Fluidez", "nivel": 1, "nombre": "Ronda de rimas", "duracion": 10, "descripcion": "El docente escribe y lee una rima corta. Los alumnos la repiten varias veces, aumentando gradualmente la velocidad.", "materiales": ["Rima corta en el pizarrón o en una tarjeta"] },
    { "area": "Fluidez", "nivel": 1, "nombre": "Lectura por minuto (Nivel 1)", "duracion": 10, "descripcion": "El alumno lee un texto muy corto durante 1 minuto. El docente cuenta cuántas palabras leyó y lo registra.", "materiales": ["Texto corto (50-80 palabras)", "Cronómetro"] },
    { "area": "Fluidez", "nivel": 1, "nombre": "El sonido de los animales", "duracion": 5, "descripcion": "El docente lee un texto y los alumnos hacen el sonido del animal mencionado. Se usa la voz para imitar.", "materiales": ["Texto con animales"] },
    { "area": "Fluidez", "nivel": 1, "nombre": "Mi frase con ritmo", "duracion": 5, "descripcion": "El docente escribe una frase corta. La lee con un ritmo de palmadas (ej. ¡Ma-ña-na-vi-a-re-mos!). Los alumnos repiten la frase con el mismo ritmo.", "materiales": ["Pizarrón", "Lista de frases cortas"] },
    { "area": "Fluidez", "nivel": 1, "nombre": "Las sílabas saltarinas", "duracion": 5, "descripcion": "El docente escribe sílabas en el pizarrón (ma, me, mi, mo, mu). Los alumnos las leen en coro. Luego el docente forma palabras combinando sílabas y los alumnos las leen.", "materiales": ["Pizarrón", "Marcador", "Tarjetas con sílabas"] },
    { "area": "Fluidez", "nivel": 2, "nombre": "Lectura en eco grupal", "duracion": 10, "descripcion": "El docente lee una estrofa o párrafo y todo el grupo lo repite al unísono. Luego se divide en dos mitades que leen alternando.", "materiales": ["Poema o canción escrita", "Pizarra"] },
    { "area": "Fluidez", "nivel": 2, "nombre": "Carrera de trabalenguas (fluidez)", "duracion": 10, "descripcion": "Se practica un trabalenguas en voz baja, luego en voz media y finalmente en voz alta, cuidando la dicción sin perder la velocidad.", "materiales": ["Tarjetas con trabalenguas"] },
    { "area": "Fluidez", "nivel": 2, "nombre": "El noticiero", "duracion": 10, "descripcion": "Cada alumno prepara la lectura de un párrafo de una noticia como si fuera un locutor. Se enfatiza claridad, velocidad y entonación.", "materiales": ["Noticias cortas", "Micrófono de juguete (opcional)"] },
    { "area": "Fluidez", "nivel": 2, "nombre": "La noticia en voz alta", "duracion": 15, "descripcion": "Los alumnos practican la lectura en voz alta de una noticia corta, cuidando la pronunciación y el ritmo. Luego la leen para un compañero.", "materiales": ["Noticia corta impresa (1 por alumno)"] },
    { "area": "Fluidez", "nivel": 2, "nombre": "Lectura por minuto (Nivel 2)", "duracion": 15, "descripcion": "El alumno lee un texto durante 1 minuto, cuenta las palabras leídas correctamente y anota su marca. Vuelve a leer para superar su propia marca.", "materiales": ["Texto corto (100-150 palabras)", "Cronómetro", "Registro de marcas"] },
    { "area": "Fluidez", "nivel": 3, "nombre": "Teatro de voces (fluidez)", "duracion": 15, "descripcion": "Se asigna un personaje a cada alumno. Leen un diálogo poniendo énfasis en la expresividad, velocidad y volumen según el personaje.", "materiales": ["Guión de diálogo corto", "Tarjetas de personajes"] },
    { "area": "Fluidez", "nivel": 3, "nombre": "Lectura expresiva con emociones", "duracion": 15, "descripcion": "El alumno recibe un mismo párrafo y debe leerlo expresando diferentes emociones (alegría, tristeza, enojo, miedo).", "materiales": ["Texto de un párrafo", "Tarjetas de emociones"] },
    { "area": "Fluidez", "nivel": 3, "nombre": "Poesía coral", "duracion": 15, "descripcion": "El grupo ensaya y presenta un poema de forma coral, asignando versos a diferentes voces para lograr un efecto rítmico y expresivo.", "materiales": ["Poema", "Marcadores para resaltar partes"] },
    { "area": "Fluidez", "nivel": 3, "nombre": "Grabación y autoevaluación", "duracion": 15, "descripcion": "El alumno se graba leyendo un texto. Luego escucha su grabación y se autoevalúa en aspectos de fluidez, entonación y ritmo.", "materiales": ["Texto", "Grabadora (celular)"] },
    { "area": "Fluidez", "nivel": 3, "nombre": "El locutor deportivo", "duracion": 10, "descripcion": "El alumno lee una narración de un partido o una noticia deportiva con la emoción y velocidad de un locutor profesional.", "materiales": ["Narración o noticia deportiva"] },

    // ============================================================
    // PRECISIÓN
    // ============================================================
    { "area": "Precisión", "nivel": 1, "nombre": "Cazador de sílabas", "duracion": 5, "descripcion": "El alumno palmea las sílabas de una palabra (ej. Ma-ri-po-sa) y busca otras con el mismo número de sílabas.", "materiales": ["Tarjetas de palabras con dibujos"] },
    { "area": "Precisión", "nivel": 1, "nombre": "Separa y lee", "duracion": 5, "descripcion": "El docente escribe palabras compuestas sin separación (ej. sacacorchos) y el alumno debe dividirlas en dos palabras.", "materiales": ["Pizarra", "Marcador"] },
    { "area": "Precisión", "nivel": 1, "nombre": "Relaciona imagen y palabra", "duracion": 10, "descripcion": "Se presentan tarjetas con imágenes y tarjetas con nombres. El alumno debe unir cada imagen con su palabra correspondiente.", "materiales": ["Tarjetas de imágenes", "Tarjetas con palabras"] },
    { "area": "Precisión", "nivel": 1, "nombre": "El sobre de palabras", "duracion": 10, "descripcion": "El alumno elige palabras, el docente las escribe en tarjetas y las guarda en un sobre. Se usan para clasificarlas y leerlas.", "materiales": ["Sobre tamaño carta", "Tarjetas de cartoncillo"] },
    { "area": "Precisión", "nivel": 2, "nombre": "El intruso (precisión)", "duracion": 10, "descripcion": "Se presenta una lista de palabras donde 4 comparten una característica (riman, misma sílaba inicial) y una no. El alumno identifica la intrusa.", "materiales": ["Listados impresos de palabras", "Lápiz"] },
    { "area": "Precisión", "nivel": 2, "nombre": "Palabras trampa (pares mínimos)", "duracion": 10, "descripcion": "El docente dice pares de palabras que se diferencian por una letra (pera/perra, casa/caza). El alumno escribe la palabra y la usa en una frase.", "materiales": ["Listado de pares mínimos", "Cuaderno"] },
    { "area": "Precisión", "nivel": 2, "nombre": "Completa la palabra (letra final)", "duracion": 10, "descripcion": "Se presenta una imagen y su palabra escrita con la última letra faltante. El alumno identifica y escribe la letra que falta.", "materiales": ["Tarjetas con imágenes y palabras incompletas", "Lápiz"] },
    { "area": "Precisión", "nivel": 2, "nombre": "Rompecabezas de sílabas", "duracion": 10, "descripcion": "El alumno recibe tarjetas con palabras divididas en sílabas desordenadas. Debe armarlas para formar la palabra correcta.", "materiales": ["Tarjetas con sílabas de varias palabras"] },
    { "area": "Precisión", "nivel": 3, "nombre": "Acentuación detectivesca", "duracion": 15, "descripcion": "Se entrega un texto sin tildes. El alumno debe colocar las tildes que faltan y leer el texto respetando la correcta acentuación.", "materiales": ["Texto sin tildes", "Bolígrafo rojo"] },
    { "area": "Precisión", "nivel": 3, "nombre": "Crucigramas (precisión)", "duracion": 15, "descripcion": "El alumno resuelve un crucigrama con palabras que contienen sílabas con dificultades ortográficas (gue/gui, ce/ci, etc.).", "materiales": ["Crucigrama impreso", "Lápiz"] },
    { "area": "Precisión", "nivel": 3, "nombre": "El ahorcado (precisión)", "duracion": 15, "descripcion": "Juego del ahorcado con palabras que presentan dificultades ortográficas específicas. Los alumnos deben adivinar la palabra letra por letra.", "materiales": ["Pizarrón", "Marcador"] },

    // ============================================================
    // ATENCIÓN A PALABRAS COMPLEJAS
    // ============================================================
    { "area": "Atención a palabras complejas", "nivel": 1, "nombre": "Subraya la palabra", "duracion": 5, "descripcion": "Se entrega un texto con palabras destacadas en negrita (ej. 'había', 'excepción'). El alumno solo debe leer esas palabras en voz alta.", "materiales": ["Texto con palabras clave en negrita"] },
    { "area": "Atención a palabras complejas", "nivel": 1, "nombre": "Memoria visual", "duracion": 5, "descripcion": "Se muestra una palabra compleja (ej. 'ferrocarril') durante 3 segundos. Luego se oculta y el alumno la escribe de memoria.", "materiales": ["Tarjetas de palabras complejas", "Pizarra individual"] },
    { "area": "Atención a palabras complejas", "nivel": 1, "nombre": "Caza de letras", "duracion": 5, "descripcion": "El docente muestra una palabra compleja y pide a los alumnos que busquen en ella una letra específica (ej. '¿Cuántas 'r' hay en ferrocarril?').", "materiales": ["Tarjetas con palabras complejas"] },
    { "area": "Atención a palabras complejas", "nivel": 2, "nombre": "Palabras trampa (atención)", "duracion": 10, "descripcion": "El docente dice pares de palabras que se diferencian por una letra (casa/caza, carro/caro). El alumno escribe y usa en frases.", "materiales": ["Listado de pares mínimos", "Cuaderno"] },
    { "area": "Atención a palabras complejas", "nivel": 2, "nombre": "Lectura con lupa", "duracion": 10, "descripcion": "Se entrega un texto con palabras complejas resaltadas. El alumno lee y, al llegar a esas palabras, las descompone en sílabas.", "materiales": ["Texto resaltado", "Lupa de cartón (opcional)"] },
    { "area": "Atención a palabras complejas", "nivel": 2, "nombre": "¡Cambia una letra!", "duracion": 10, "descripcion": "El docente escribe una palabra y los alumnos deben cambiarla, modificando una sola letra, para formar una palabra nueva.", "materiales": ["Pizarrón", "Marcador"] },
    { "area": "Atención a palabras complejas", "nivel": 3, "nombre": "Análisis morfológico exprés", "duracion": 15, "descripcion": "El alumno lee un párrafo y subraya prefijos y sufijos (ej. 'inútil', 'felicidad'), explicando cómo cambia el significado de la raíz.", "materiales": ["Párrafo con palabras derivadas", "Marcador"] },
    { "area": "Atención a palabras complejas", "nivel": 3, "nombre": "Palabras compuestas", "duracion": 15, "descripcion": "El alumno identifica y escribe palabras compuestas (ej. abrelatas, sacapuntas, mediodía). Luego las usa en oraciones.", "materiales": ["Lista de palabras compuestas", "Cuaderno"] },
    { "area": "Atención a palabras complejas", "nivel": 3, "nombre": "Homófonas", "duracion": 15, "descripcion": "El alumno trabaja con palabras homófonas (ej. 'tubo' y 'tuvo', 'valla' y 'vaya'). Escribe oraciones con cada una para comprender su significado.", "materiales": ["Lista de palabras homófonas", "Diccionario"] },

    // ============================================================
    // USO DE LA VOZ
    // ============================================================
    { "area": "Uso de la voz", "nivel": 1, "nombre": "Respiración de globo", "duracion": 5, "descripcion": "Ejercicio de respiración: inflar un globo al inspirar y desinflarlo al espirar diciendo 'sssss'. Luego leer una frase con el aire controlado.", "materiales": ["Ninguno (imaginería)"] },
    { "area": "Uso de la voz", "nivel": 1, "nombre": "El teléfono descompuesto (voz)", "duracion": 5, "descripcion": "Los alumnos se sientan en fila. El primero susurra una palabra al oído del siguiente. Se trabaja la claridad al hablar.", "materiales": ["Ninguno"] },
    { "area": "Uso de la voz", "nivel": 1, "nombre": "Eco de volumen", "duracion": 5, "descripcion": "El docente lee una palabra en voz baja y el alumno la repite. Luego en voz alta y el alumno repite. Control de intensidad.", "materiales": ["Lista de palabras"] },
    { "area": "Uso de la voz", "nivel": 2, "nombre": "Modulación de emociones (voz)", "duracion": 10, "descripcion": "Se entrega una misma oración y el alumno debe leerla con tono de: alegría, tristeza, sorpresa y enojo.", "materiales": ["Tarjetas de emociones", "Frase modelo"] },
    { "area": "Uso de la voz", "nivel": 2, "nombre": "Yo, el locutor", "duracion": 10, "descripcion": "El alumno lee una noticia corta imitando la voz de un locutor de radio o televisión, cuidando el volumen y la claridad.", "materiales": ["Noticia corta", "Micrófono de juguete"] },
    { "area": "Uso de la voz", "nivel": 2, "nombre": "El viento y el trueno", "duracion": 10, "descripcion": "Se practica el volumen. Para un texto sobre una tormenta, el alumno usa voz suave (viento) y voz fuerte (trueno).", "materiales": ["Texto con elementos de volumen"] },
    { "area": "Uso de la voz", "nivel": 3, "nombre": "Locución de noticias", "duracion": 15, "descripcion": "El alumno lee una noticia como locutor de radio, cuidando el volumen, las pausas y la entonación. Se graba y se autoevalúa.", "materiales": ["Noticia corta", "Grabadora (celular)"] },
    { "area": "Uso de la voz", "nivel": 3, "nombre": "Teatro de voces (voz)", "duracion": 15, "descripcion": "Se asigna un personaje a cada alumno. Leen un diálogo poniendo énfasis en la expresividad, velocidad y volumen según el personaje.", "materiales": ["Guión de diálogo", "Tarjetas de personajes"] },
    { "area": "Uso de la voz", "nivel": 3, "nombre": "Poesía con efectos de sonido", "duracion": 15, "descripcion": "Se prepara una poesía coral que incluye efectos de sonido con la voz (susurros, ecos, onomatopeyas) para dar mayor expresividad.", "materiales": ["Poema", "Instrumentos de percusión"] },

    // ============================================================
    // SEGURIDAD Y DISPOSICIÓN
    // ============================================================
    { "area": "Seguridad y disposición", "nivel": 1, "nombre": "Ritual de inicio", "duracion": 5, "descripcion": "Antes de leer, el alumno se sienta recto, respira profundo y dice: 'Estoy listo para leer'. Activa su disposición.", "materiales": ["Ninguno"] },
    { "area": "Seguridad y disposición", "nivel": 1, "nombre": "El espejo positivo", "duracion": 5, "descripcion": "El alumno se mira en un espejo pequeño mientras se dice a sí mismo: 'Soy un buen lector' y lee una frase corta mirándose a los ojos.", "materiales": ["Espejo pequeño"] },
    { "area": "Seguridad y disposición", "nivel": 1, "nombre": "¿Qué puedo leer?", "duracion": 5, "descripcion": "Exploración libre de la biblioteca del aula. Cada alumno elige un libro que le llame la atención, solo por su portada o título.", "materiales": ["Libros de la biblioteca del aula"] },
    { "area": "Seguridad y disposición", "nivel": 1, "nombre": "Lectura en voz baja para mí", "duracion": 5, "descripcion": "Se pide a los alumnos que lean en voz baja o susurrada un texto corto, sin la presión de un público.", "materiales": ["Texto corto para cada alumno"] },
    { "area": "Seguridad y disposición", "nivel": 2, "nombre": "Mis logros lectores", "duracion": 10, "descripcion": "El alumno lee un texto fácil y registra en su 'diario de lector' cuántas palabras leyó bien y qué hizo bien.", "materiales": ["Diario de lector", "Texto corto"] },
    { "area": "Seguridad y disposición", "nivel": 2, "nombre": "Aplausos por párrafo", "duracion": 10, "descripcion": "Por cada párrafo que el alumno lee sin errores, el grupo da una palmada. Se refuerza el esfuerzo y la atención sostenida.", "materiales": ["Texto por párrafos"] },
    { "area": "Seguridad y disposición", "nivel": 2, "nombre": "El lector recomendado", "duracion": 10, "descripcion": "Un alumno que ha leído un libro lo recomienda a sus compañeros, describiendo de qué trata y por qué le gustó.", "materiales": ["Libro leído previamente"] },
    { "area": "Seguridad y disposición", "nivel": 3, "nombre": "Lectura en cámara lenta", "duracion": 15, "descripcion": "El alumno lee un texto desafiante extremadamente lento, enfocándose en cada palabra. El objetivo es la autoconfianza.", "materiales": ["Texto de nivel superior", "Cronómetro"] },
    { "area": "Seguridad y disposición", "nivel": 3, "nombre": "El club de los lectores", "duracion": 15, "descripcion": "Se reúne un grupo pequeño para comentar un libro que todos han leído. Cada alumno comparte su opinión sin ser evaluado.", "materiales": ["Libro leído en común"] },
    { "area": "Seguridad y disposición", "nivel": 3, "nombre": "Mi lectura favorita", "duracion": 15, "descripcion": "Cada alumno elige su texto favorito y lo lee al grupo, explicando por qué le gusta. Se celebra la diversidad de gustos.", "materiales": ["Texto elegido por el alumno"] },

    // ============================================================
    // COMPRENSIÓN LECTORA
    // ============================================================
    { "area": "Comprensión lectora", "nivel": 1, "nombre": "Dibuja lo que lees", "duracion": 15, "descripcion": "El alumno lee una oración simple (ej. 'El perro corre bajo la lluvia') y hace un dibujo. Luego explica su dibujo a un compañero.", "materiales": ["Oraciones ilustrables", "Hojas en blanco", "Colores"] },
    { "area": "Comprensión lectora", "nivel": 1, "nombre": "Ordena la historia", "duracion": 10, "descripcion": "Se entregan 4 viñetas desordenadas de un cuento conocido. El alumno las ordena y cuenta la historia con sus palabras.", "materiales": ["Viñetas impresas", "Tijeras"] },
    { "area": "Comprensión lectora", "nivel": 1, "nombre": "¿Qué pasó primero?", "duracion": 10, "descripcion": "Se lee un cuento corto. Luego se muestran 3 dibujos de la historia y se pregunta cuál pasó primero, después y al final.", "materiales": ["Cuento corto", "Dibujos"] },
    { "area": "Comprensión lectora", "nivel": 1, "nombre": "El personaje favorito", "duracion": 10, "descripcion": "Después de una lectura, el alumno elige su personaje favorito y lo describe con sus palabras (cómo es, qué hace, por qué le gusta).", "materiales": ["Cuento leído"] },
    { "area": "Comprensión lectora", "nivel": 1, "nombre": "Sigue las instrucciones", "duracion": 10, "descripcion": "El docente da instrucciones orales sencillas (ej. 'Toca tu cabeza, luego toca tu nariz'), los alumnos las siguen. Luego se lee una instrucción sencilla en voz alta para que la sigan.", "materiales": ["Tarjetas con instrucciones"] },
    { "area": "Comprensión lectora", "nivel": 2, "nombre": "Preguntas de colores", "duracion": 15, "descripcion": "Después de leer, se formulan preguntas: Rojo (¿Quién?), Azul (¿Dónde?), Verde (¿Cuándo?), Naranja (¿Por qué?). El alumno responde señalando la evidencia en el texto.", "materiales": ["Texto", "Tarjetas de colores", "Marcadores"] },
    { "area": "Comprensión lectora", "nivel": 2, "nombre": "El titular", "duracion": 10, "descripcion": "Después de leer un texto breve, el alumno inventa 3 posibles titulares y elige el que mejor resuma la idea principal.", "materiales": ["Texto breve", "Pizarra o papel"] },
    { "area": "Comprensión lectora", "nivel": 2, "nombre": "El resumen con 5 dedos", "duracion": 10, "descripcion": "Técnica del resumen con los 5 dedos: Pulgar (Personajes), Índice (Lugar), Corazón (Problema), Anular (Solución), Meñique (Final).", "materiales": ["Texto leído", "Hoja de trabajo"] },
    { "area": "Comprensión lectora", "nivel": 2, "nombre": "¿Qué pasaría si...?", "duracion": 10, "descripcion": "Se plantean preguntas hipotéticas sobre un texto leído (ej. '¿Qué pasaría si el personaje principal no hubiera hecho eso?').", "materiales": ["Texto leído"] },
    { "area": "Comprensión lectora", "nivel": 3, "nombre": "Inferencias en cadena", "duracion": 15, "descripcion": "Se lee un microcuento donde no todo está explícito. El alumno responde: ¿Qué pasó antes? ¿Qué pasará después? justificando con pistas.", "materiales": ["Microcuento o noticia", "Hoja de inferencias"] },
    { "area": "Comprensión lectora", "nivel": 3, "nombre": "El debate (comprensión)", "duracion": 15, "descripcion": "Se lee un texto con un tema polémico. El grupo se divide para argumentar a favor y en contra, usando la información del texto.", "materiales": ["Texto polémico"] },
    { "area": "Comprensión lectora", "nivel": 3, "nombre": "La historia desde otro punto de vista", "duracion": 15, "descripcion": "Después de leer un cuento, el alumno reescribe una escena desde la perspectiva de otro personaje (ej. el lobo en Caperucita Roja).", "materiales": ["Cuento", "Cuaderno"] },
    { "area": "Comprensión lectora", "nivel": 3, "nombre": "Compara y contrasta", "duracion": 15, "descripcion": "Se leen dos textos sobre un mismo tema. El alumno llena un diagrama de Venn para comparar la información presentada.", "materiales": ["Dos textos sobre el mismo tema", "Hoja de trabajo"] },
    { "area": "Comprensión lectora", "nivel": 3, "nombre": "El mapa conceptual", "duracion": 15, "descripcion": "El alumno elabora un mapa conceptual de un texto informativo, identificando el tema principal y las ideas secundarias.", "materiales": ["Texto informativo", "Hoja y colores"] }
];
